### ISSUE TITLE
Auth issue when running on same FQDN

### ISSUE THREAD

**Issue by Synapse791** [SUSE/Portus#523] opened 2015-10-30 17:42 UTC
I've been trying to set up Portus for our private registry today and am getting an issue with the login part using the docker cli.

I can log into the UI perfectly fine, and when I do the following curl request, I get back a 200 Response with a token.

```
curl -ik --user user1:password1 "https://myregistry.net/portus/v2/token?account=$user&service=myregistry.net"
```

That part of the process seems to be working fine. The problem comes when I try to use that token. Running the following curl request gives me a 401 with an invalid_token message.

```
curl -i -H "Authorization: Bearer MY_TOKEN" https://myregistry.net/v2/
```

Auth section of my registry config:

```
auth:
  token:
    realm: https://myregistry.net/portus/v2/token
    service: myregistry.net
    issuer: myregistry.net
    rootcertbundle: /etc/docker/registry/ssl/myregistry.net.cert
```

The SSL certificate is the same as the one I'm using in the apache2 configuration which is working and telling me my certificate is valid and authorized.

**Extra Info**
- Error from docker login: 

```
    Error response from daemon: no successful auth challenge for https://myregistry.net/v2/ - errors: [token auth attempt to https://myregistry.net/v2/ realm "https://myregistry.net/portus/v2/token" failed with status: 401 Unauthorized]
```
- All components running on the same server
- Apache is running on port 443
- Registry is running on port 5000
- MariaDB is running on port 3306 and has the user in the DB. the user can also log into the UI using the same username and password

**Comment by kooltux** [comment] 2015-10-30 19:33
duplicate of https://github.com/SUSE/Portus/issues/509 ?

**Comment by mssola** [comment] 2015-11-02 08:50
We wrote a wiki page about this: https://github.com/SUSE/Portus/wiki/Portus-and-Docker-registry-on-the-same-FQDN-using-sub-URI. And as @kooltux is saying, issue #509 has a discussion about this.

For more information, you might also want to take a look at the logs (`log/development.log`). Same common pitfalls are not setting the registry properly in the admin page (not specifying the port on the hostname, forgetting about un/setting the SSL checkbox, etc.).

**Comment by kooltux** [comment] 2015-11-03 09:16
I cross-post my comment from #509 because I feel it's more related to this issue. 

@synapse791, if you look at the portus log (/srv/Portus/log/*.log), do you see the same problem as me, that is: the user 'portus' can't obtain a token and log on the registry after a successful 'docker push' ?

I followed your document on the [wiki](https://github.com/SUSE/Portus/wiki/Portus-and-Docker-registry-on-the-same-FQDN-using-sub-URI) and got a partially working setup.

FYI, I branched the docker-distrubution package on Suse OBS to include this [PR](https://github.com/docker/distribution/pull/1142) which is not accepted on upstream project docker/docker-distribution: see my [project](https://build.opensuse.org/package/show/home:kooltux/docker-distribution). The download repo is [here](http://download.opensuse.org/repositories/home:/kooltux/openSUSE_13.2/)

What works:
* docker login ok
* docker push ok
* docker pull ok

But there's still a problem for portus to access the registry. In /srv/Portus/logs/production.log, I get:
```
I, [2015-10-30T16:07:15.112410 #22682]  INFO -- : Started GET "/portus/v2/token?scope=repository%3Adevel%2Fbusybox%3Apush%2Cpull&service=127.0.0.1%3A5000" for 46.18.96.42 at 2015-10-30 16:07:15 +0100
I, [2015-10-30T16:07:15.113127 #22682]  INFO -- : Processing by Api::V2::TokensController#show as JSON
I, [2015-10-30T16:07:15.113180 #22682]  INFO -- :   Parameters: {"scope"=>"repository:devel/busybox:push,pull", "service"=>"127.0.0.1:5000"}
I, [2015-10-30T16:07:15.115359 #22682]  INFO -- : Denied access on these grounds: not allowed to  this nil
I, [2015-10-30T16:07:15.115501 #22682]  INFO -- : Completed 401 Unauthorized in 2ms (ActiveRecord: 0.5ms)
```
Given the message "not allowed to this nil", this means that portus doesn't want to deliver a token to 'nil', which means that a param is probably missing...

**Comment by Synapse791** [comment] 2015-11-03 09:49
Thanks @kooltux 

When attempting to run the catalog crono task, I get the following log entries:
```
I, [2015-11-03T09:20:39.649082 #21147]  INFO -- : Started GET "/portus/v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=myregistry.net" for 10.100.1.1 at 2015-11-03 09:20:39 +0000
I, [2015-11-03T09:20:39.650158 #21147]  INFO -- : Processing by Api::V2::TokensController#show as JSON
I, [2015-11-03T09:20:39.650297 #21147]  INFO -- :   Parameters: {"account"=>"portus", "scope"=>"registry:catalog:*", "service"=>"myregistry.net"}
I, [2015-11-03T09:20:39.735337 #21147]  INFO -- : Completed 200 OK in 85ms (Views: 1.8ms | ActiveRecord: 3.6ms)
W, [2015-11-03T09:20:39.746095 #11026]  WARN -- : Exception: Something went wrong while fetching the catalog Response: [401] - {"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":[{"Type":"registry","Name":"catalog","Action":"*"}]}]}
```

So for me, this looks like the registry is providing the correct token response but then when it tries to use the token for a request, it fails to verify that token. I get the same logs minus the last entry when doing a docker login as well.

After some more digging, I found this line in the docker registry logs:

    time="2015-11-03T09:41:34.412417063Z" level=error msg="token from untrusted issuer: \"ip-10-100-1-1.localdomain\""

If you check the configuration in my initial post, you'll see that I set the issuer as `myregistry.net`. It seems like this setting isn't getting used for the token generation?

**Comment by Synapse791** [comment] 2015-11-03 10:12
More digging, I found that I can set the issuer in Portus in the config/secrets.yml using the `machine_fqdn` option. Setting that then gave me a new error in the registry logs:

    time="2015-11-03T09:57:26.715937138Z" level=error msg="token signed by untrusted key with ID: \"KEY_ID_HERE\""

This got me thinking about the SSL certificates and keys so I went into the Portus/config directory and found a symlink to some random SSL key. I changed it to point at the key for my ssl certificate and now I can login to the registry with no problem!

Now my only issue is with the portus user not being able to access the tag list of a repository. Running the catalog command again tells me it finished in 6.40 seconds but nothing shows in the UI. Back into the registry logs and I see this:

```
172.17.42.1 - - [03/Nov/2015:10:07:12 +0000] "GET /v2/_catalog HTTP/1.1" 200 716 "" "Ruby"
time="2015-11-03T10:07:18.266231546Z" level=warning msg="error authorizing context: insufficient scope" http.request.host="127.0.0.1:5000" http.request.id=e5ece76b-2000-4cdf-803e-16b099232276 http.request.method=GET http.request.remoteaddr=10.100.1.1 http.request.uri="/v2/my/image/tags/list" http.request.useragent=Ruby instance.id=ID_HERE service=registry vars.name="my/image" version=v2.1.1 
172.17.42.1 - - [03/Nov/2015:10:07:18 +0000] "GET /v2/my/image/tags/list HTTP/1.1" 401 180 "" "Ruby"
```

From this I can see that it's successfully loading the catalog of repositories but then doesn't have the access to get the tag list of each repository.

**Comment by mssola** [comment] 2015-11-03 10:35
@Synapse791 another way to check that your configuration is working, is by executing:

    $ bundle exec rails r bin/client.rb manifest

Anyways, in this case, maybe it should be useful to check at Portus' logs. It should give us more information about why is that you're not authorized to fetch the tag list.

**Comment by mssola** [comment] 2015-11-03 10:41
@kooltux ok, that message can certainly be improved from our side... My bet is that:

    Denied access on these grounds: nil

This happens only when the following has been executed:

```ruby
raise Pundit::NotAuthorizedError if auth_scope.actions.empty?
```

This happens only happens when you're not authorized to do that. Since this is the portus user who is performing this request, maybe this `devel` namespace does not exist in Portus ?

**Comment by Synapse791** [comment] 2015-11-03 12:48
Thanks @mssola 

I have executed the following command:

    RAILS_ENV=production bundle exec rails r bin/client.rb manifest

And I get the following response:

    You have to at least specify the name of the image

I assumed I had to put the image name on the end of the command which gave me this response:

```
RAILS_ENV=production bundle exec rails r bin/client.rb manifest test/httpd
bin/client.rb:38:in `<top (required)>': undefined method `pp' for main:Object (NoMethodError)
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/runner.rb:60:in `load'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /srv/Portus/vendor/bundle/ruby/2.1.0/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

Logs:
```
I, [2015-11-03T12:43:17.495733 #2400]  INFO -- : Started GET "/portus/v2/token?account=portus&scope=repository%3Atest%2Fhttpd%3Apull&service=myregistry.net" for 10.100.1.1 at 2015-11-03 12:43:17 +0000
I, [2015-11-03T12:43:17.496897 #2400]  INFO -- : Processing by Api::V2::TokensController#show as JSON
I, [2015-11-03T12:43:17.496961 #2400]  INFO -- :   Parameters: {"account"=>"portus", "scope"=>"repository:test/httpd:pull", "service"=>"myregistry.net"}
I, [2015-11-03T12:43:17.584783 #2400]  INFO -- : Completed 200 OK in 88ms (Views: 2.0ms | ActiveRecord: 4.6ms)
I, [2015-11-03T12:43:18.024754 #2400]  INFO -- : Started POST "/portus/v2/webhooks/events" for 172.17.0.13 at 2015-11-03 12:43:18 +0000
I, [2015-11-03T12:43:18.025751 #2400]  INFO -- : Processing by Api::V2::EventsController#create as JSON
I, [2015-11-03T12:43:18.026174 #2400]  INFO -- : Completed 202 Accepted in 0ms (ActiveRecord: 0.0ms)
```

**Comment by mssola** [comment] 2015-11-03 12:54
@Synapse791 just go to the client.rb file and add `require 'pp'` on top of it.

**Comment by Synapse791** [comment] 2015-11-03 13:02
Thanks! Sorry, I'm not a Ruby guy.

So that worked fine and returned all the data on that image but when I run the catalog command, it fails to authorize

    ~$ RAILS_ENV=production bundle exec rails r bin/client.rb catalog
    /srv/Portus/lib/portus/http_helpers.rb:108:in `request_auth_token': Cannot obtain authorization token: #<Net::HTTPUnauthorized:0x00000007a4a1f8> (Portus::HttpHelpers::AuthorizationError)

**Comment by mssola** [comment] 2015-11-03 13:11
@Synapse791 wow, that's weird :/ Since you're on production mode, could you relax the logging level a bit to debug this issue ? You can do that by modifying the file `config/environments/production.rb` changing the line:

```ruby
config.log_level = :info
```

To `:debug`. Then  call the `catalog` command. Paste what has been logged then.

**Comment by kooltux** [comment] 2015-11-03 13:56
@mssola: in my tests, the 'devel' namespace exists, as I pushed a busybox image in it. The error occurs when portus reacts to the 'webhooks/events' call and reconnects on registry to get the details on the recently pushed image

I'll raise the loglevel to get more verbose logs.

**Comment by kooltux** [comment] 2015-11-03 15:08
Very strange. Now, I'm unable to reproduce the problem... For me, nothing changed since I reported it.

Now, I get the following message in portus log and this time, the 'account' key is set when the token is generated for 'portus' user:
```
I, [2015-11-03T16:02:00.532002 #29161]  INFO -- : Started GET "/portus/v2/token?account=portus&scope=repository%3Adevel%2Fbusybox%3Apull&service=127.0.0.1%3A5000" for 51.254.0.101 at 2015-11-03 16:02:00 +0100
I, [2015-11-03T16:02:00.542617 #29161]  INFO -- : Processing by Api::V2::TokensController#show as JSON
I, [2015-11-03T16:02:00.542703 #29161]  INFO -- :   Parameters: {"account"=>"portus", "scope"=>"repository:devel/busybox:pull", "service"=>"127.0.0.1:5000"}
I, [2015-11-03T16:02:00.694065 #29161]  INFO -- : Completed 200 OK in 151ms (Views: 1.6ms | ActiveRecord: 52.8ms)
I, [2015-11-03T16:02:00.709223 #25416]  INFO -- : Completed 202 Accepted in 1900ms (ActiveRecord: 1.0ms)
```

**Comment by Synapse791** [comment] 2015-11-03 15:13
Only got 2 extra log lines from changing it to debug and it was just SQL queries.

```
D, [2015-11-03T14:47:55.217218 #12311] DEBUG -- :   ActiveRecord::SchemaMigration Load (0.2ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
D, [2015-11-03T14:47:55.268551 #12311] DEBUG -- :   Registry Load (0.2ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1
```

I have noticed though that it's complaining about the first namespace in the catalog not existing. This is because I ran the docker-registry migrator to move from our v1 registry to the v2 one. I have changed the rootdirectory setting for the registry so it's fresh and now the catalog command finishes fine! Seems like if the namespace isn't there in portus, the image can't be catalogued correctly.

Now I have switched the registry to an empty folder with no repositories, when I try to push to a namespace that exists in Portus that I have access to, I get a `Method not allowed` response from Apache. Is there a setting I'm missing in the apache config?

```
    RewriteEngine On

   RewriteCond %{REQUEST_URI} !^/portus.*$
   RewriteRule ^/(.*)$ "http:\/\/127\.0\.0\.1\:5000\/$1" [P,L]

   Alias /portus /srv/Portus/public
   <Location /portus>
     PassengerBaseURI /portus
     PassengerAppRoot /srv/Portus
   </Location>

   <Directory /srv/Portus/public>
      # This relaxes Apache security settings.
      AllowOverride all
      # MultiViews must be turned off.
      Options -MultiViews
      # Uncomment this if you're on Apache >= 2.4:
      Require all granted
      SetEnv GEM_PATH /srv/Portus/vendor/bundle/ruby/2.1.0
      SetEnv PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY 0
      SetEnv PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY 0
      PassengerAppEnv production
   </Directory>
```

Seems to me that Apache shouldn't be blocking that as it's a straight proxy to the registry?

**Comment by rennhak** [comment] 2016-04-05 23:09
+1

**Comment by sergioasantiago** [comment] 2016-04-06 19:12
I'm getting a similar error. We use a slightly different approach:

We have 3 docker containers:

1 - Nginx container: SSL termination and proxy_pass to portus and registry.
Nginx config file:
```
location / {
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass http://portus;
  }

  location /v2/token {
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass http://portus;
  }

  location /v2/webhooks/events {
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass http://portus;
  }

  location /v2 {
    client_max_body_size 0;
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass http://registry;
  }
```
2 - Portus container: Portus instance. Using last upstream source from master branch.
Portus configure Registry using `mydomain.com:5000`

3 - Registry container: Registry instance, version 2.3.1
Registry config file:
```
version: 0.1
loglevel: info
storage:
  filesystem:
    rootdirectory: /var/lib/docker-registry
  delete:
    enabled: true
http:
  addr: :5000
redis:
  addr: localhost:6379
auth:
  token:
    realm: https://mydomain.com/v2/token
    service: mydomain.com:5000
    issuer: mydomain.com
    rootcertbundle: /etc/ssl/mydomain.crt
notifications:
  endpoints:
    - name: portus
      url: http://mydomain.com:3000/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s
```

Both Portus container and Registry container have in `/etc/hosts` an entry mapping `mydomain.com` to docker bridge, in order to allow me access, from inside each container, each other using mydomain.com:3000 and mydomain.com:5000, skipping SSL, since they are in the same host.

That said, after all this setup and everything running (and some strokes and white hairs) I could manage to make everything talking with everything.
Well everything was good, until when I notice that Portus was not showing notifications in its UI. So checking logs I got this:
```
Handling Push event:
{ 
  "id": "808ec723-4b26-415b-8f95-f534c876b3fd",
  "timestamp": "2016-04-05T22:47:44.050146264Z",
  "action": "push",
  "target": {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 708,
    "digest": "sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf",
    "length": 708,
    "repository": "sergio/hello-world",
    "url": "https://mydomain.com/v2/sergio/hello-world/manifests/sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf"
  },
  "request": {
    "id": "caad4710-8800-4a06-ab65-fa982a7eddb9",
    "addr": "172.17.0.1",
    "host": "mydomain.com",
    "method": "PUT",
    "useragent": "docker/1.10.2 go/go1.5.3 git-commit/c3959b1 kernel/3.16.0-4-amd64 os/linux arch/amd64"
  },
  "actor": {
    "name": "sergio"
  },
  "source": {
    "addr": "b6f3b57fb71e:5000",
    "instanceID": "99c056d4-dfb9-42c4-b33c-c2fb956afb56"
  }
}
Ignoring event coming from unknown registry
                  mydomain.com
```

Highlighting this: `Ignoring event coming from unknown registry mydomain.com`
Which makes sense since Registry in Portus is: `mydomain.com:5000`

After some more white hairs, I could only manage to make it works patching portus base code changing this line:
https://github.com/SUSE/Portus/blob/master/app/models/registry.rb#L37

To this:
```ruby
registry = Registry.where("hostname LIKE ?", "%#{event['request']['host']}%").first
```

Which is an ugly workaround, but temporally solved my problem.

I noticed that docker team closed [this issue] (https://github.com/docker/distribution/pull/1142) since it's not a bug in their side.
So after this small Mexican soup-opera  my point is, what is the final verdict?

**Comment by mssola** [comment] 2017-08-02 15:28
We have written some examples, and of them uses the same FQDN for everything. So I'm going to close this, but if you have more doubts feel free to leave some comments.

**Closed by mssola** 2017-08-02 15:28 UTC
Labels: needs info
