### ISSUE TITLE
RAILS_RELATIVE_URL_ROOT not correctly honoured

### ISSUE THREAD

**Issue by phasenohr** [SUSE/Portus#1609] opened 2018-01-22 15:15 UTC
In the opensuse/portus:head version of 21/01/2018 (build bfbyoe5kxdzv75gzqryl8fx), the environment variable `RAILS_RELATIVE_URL_ROOT` is not correctly handled.
I deploy Portus at https://internal1_fqdn/apps/portus/ in order to be accessible through a reverse proxy listening at https://external_fqdn/apps/portus/

I configured `RAILS_RELATIVE_URL_ROOT=/apps/portus/` 

The GUI is correctly displayed but many actions fail (create/edit/delete a team, namespace etc.). Looking at the logs in the debug console of my browser, I could see the following urls being called: /assets, /api/v1, /namespaces, /tags, /teams
All of them work correctly if prefixed with /apps/portus/ (e.g. /apps/portus/assets, /apps/portus/api/v1, etc.)

This is a major blocker for deployment in a production environment. Would it be possible to fix it in time for the release of 2.3.0 (or ideally before)?
Thanks.
Paul

**Comment by mssola** [comment] 2018-01-22 15:53
Duplicate of #1608 😉 Let's track this issue there. There's a PR already open (#1610), which we will merge as soon as possible, and it will be included in the 2.3 release (the release is not there yet, so we can still accept last-minute fixes 👍)

**Closed** 2018-01-22 15:52 UTC
Labels: bug, duplicate

**Comment by mssola** [comment] 2018-01-22 15:55
Just cherry-picked into the `v2.3` branch. We only need to wait until Docker images are rebuilt with the new code. Thanks for reporting 👍
