### ISSUE TITLE
Hint which users can be selected when adding a member to a team

### ISSUE THREAD

**Issue by mssola** [SUSE/Portus#103] opened 2015-06-11 13:05 UTC
Right now, you have to know the name of the user before adding to it. It would be much better if there were some kind of auto-completion when adding members to a team.

One idea is to use the [chosen](http://harvesthq.github.io/chosen/) library.

**Comment by flavio** [comment] 2015-06-11 14:48
Duplicate of #39

**Comment by mssola** [comment] 2015-06-11 14:48
ahh, good catch, sorry about that :)

**Closed by flavio** 2015-06-11 14:48 UTC
Labels: ux
