### ISSUE TITLE
feature request: show and copy pull command

### ISSUE THREAD

**Issue by AndreasKrause** [SUSE/Portus#1108] opened 2016-10-25 14:33 UTC
It would be convinient for the user if Portus showed the command to pull a certain image from the registry.

Given Portus shows repository contents at `https://portus.example.com/repositories/<repository_id>`. There's a table listing all images, all of which can be tagged multiple times. Now, here's the requested feature: By clicking the tag, the user should have the command line needed to pull that very tag into his clipboard buffer.

Command line should be like `docker pull <registry_fqdn>/<namespace>/<repository>:<tag>`
Note that `registry_fqdn` might differ drom `portus_fqdn`.

**Comment by holgerreif** [comment] 2016-10-25 15:06
There was some work underway in #697.

**Comment by mssola** [comment] 2016-10-27 11:30
Agreed. This looks like a duplicate of #697, but it adds more elements that are interesting, so I'll keep it open :wink:

**Closed** 2017-09-07 07:52 UTC
