### ISSUE TITLE
ERROR: Cannot link to a non running container: /portus_web_1 AS /portus_registry_1/portus_web_1

### ISSUE THREAD

**Issue by yeruisen** [SUSE/Portus#1033] opened 2016-08-15 07:49 UTC
**When I run  ./compose-setup.sh -f -e 192.168.1.23 ,and end:**

```
_Creating portus_db_1

Creating portus_web_1

Creating portus_registry_1

ERROR: Cannot link to a non running container: /portus_web_1 AS /portus_registry_1/portus_web_1_
```

**When I run docker-compose up:**
```
`[root@localhost Portus]# docker-compose up

portus_db_1 is up-to-date
Starting portus_web_1
Starting portus_registry_1
Creating portus_crono_1
Attaching to portus_db_1, portus_web_1, portus_registry_1, portus_crono_1
registry_1 | configuration error: open /etc/docker/registry/config.yml: permission denied
registry_1 |
web_1      | /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/definition.rb:23:in `build': /portus/Gemfile not found (Bundler::GemfileNotFound)
registry_1 | Usage:
web_1      | 	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler.rb:155:in `definition'
web_1      | 	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler.rb:123:in `setup'
crono_1    | /bin/bash: bin/crono: Permission denied
web_1      | 	from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/setup.rb:18:in `<top (required)>'
web_1      | 	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
web_1      | 	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
web_1      | 	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
web_1      | 	from /usr/local/bundle/bin/puma:14:in `<main>'
registry_1 |   registry <config> [flags]
registry_1 | Flags:
registry_1 |   -h, --help=false: help for registry
registry_1 |   -v, --version=false: show the version and exit
registry_1 |
portus_web_1 exited with code 1
portus_registry_1 exited with code 1
db_1       | Initializing database
db_1       | 160815  7:59:37 [Note] /usr/sbin/mysqld (mysqld 10.0.23-MariaDB-1~jessie) starting as process 74 ...
db_1       | 160815  7:59:37 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1       | 160815  7:59:37 [Note] InnoDB: The InnoDB memory heap is disabled
db_1       | 160815  7:59:37 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1       | 160815  7:59:37 [Note] InnoDB: Memory barrier is not used
db_1       | 160815  7:59:37 [Note] InnoDB: Compressed tables use zlib 1.2.8`

```

**Comment by monstermunchkin** [comment] 2016-08-15 13:10
It seems you have some troubles with file permissions, hence the message `open […] permission denied`. Please make sure the file `config/registry/config.yml` has read permissions set (e.g. 0644).

Also, `bin/crono` seems to have a similar issue. The permission should be 0755.

If this doesn't help, please try doing a fresh `git clone` of Portus and let us know if the issue remains.

**Comment by nohtyp** [comment] 2016-08-15 20:28
The issue still remains.  I just downloaded the repo and still get the same error.

**Comment by yeruisen** [comment] 2016-08-16 01:20
When I run on my mac virtualbox ,and docker verson is 1.11.2, compose version is 1.8, install Portus is ok,but when I run on my centos 7.2 ,then docker version is 1.10.3, and compose version is 1.6, install Portus failed.

**Comment by FishGel** [comment] 2016-08-16 01:32
```
[root@registry portus]# ./compose-setup.sh 
The setup will destroy the containers used by Portus, removing also their volumes.
Are you sure to delete all the data? (Y/N) Y
Killing portus_db_1 ... done
Going to remove portus_registry_1, portus_web_1, portus_db_1
Removing portus_registry_1 ... done
Removing portus_web_1 ... done
Removing portus_db_1 ... done
Creating portus_db_1
Creating portus_web_1
Creating portus_registry_1
ERROR: Cannot link to a non running container: /portus_web_1 AS /portus_registry_1/portus_web_1

```

**portus_web cannot start.
Blew is portus_web container's log.**
```
[root@registry portus]# docker  logs 204b9241ad6e
/usr/local/bundle/gems/bundler-1.10.4/lib/bundler/definition.rb:23:in `build': /portus/Gemfile not found (Bundler::GemfileNotFound)
        from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler.rb:155:in `definition'
        from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler.rb:123:in `setup'
        from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/setup.rb:18:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /usr/local/bundle/bin/puma:14:in `<main>'
```

**Comment by yeruisen** [comment] 2016-08-16 01:47
**When I run on my mac virtualbox ,and docker verson is 1.11.2, compose version is 1.8, install Portus is ok,but when I run on my centos 7.2 ,then docker version is 1.10.3, and compose version is 1.6, install Portus failed. @monstermunchkin**

```
[root@registry portus]# ./compose-setup.sh 
The setup will destroy the containers used by Portus, removing also their volumes.
Are you sure to delete all the data? (Y/N) Y
Killing portus_db_1 ... done
Going to remove portus_registry_1, portus_web_1, portus_db_1
Removing portus_registry_1 ... done
Removing portus_web_1 ... done
Removing portus_db_1 ... done
Creating portus_db_1
Creating portus_web_1
Creating portus_registry_1
ERROR: Cannot link to a non running container: /portus_web_1 AS /portus_registry_1/portus_web_1
[root@registry portus]# docker-compose up
portus_db_1 is up-to-date
Starting portus_web_1
Starting portus_registry_1
Creating portus_crono_1
Attaching to portus_db_1, portus_web_1, portus_registry_1, portus_crono_1
web_1      | /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/definition.rb:23:in `build': /portus/Gemfile not found (Bundler::GemfileNotFound)
web_1      |    from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler.rb:155:in `definition'
web_1      |    from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler.rb:123:in `setup'
web_1      |    from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/setup.rb:18:in `<top (required)>'
web_1      |    from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
registry_1 | /bin/bash: /registry/entry.sh: Permission denied
web_1      |    from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
web_1      |    from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
web_1      |    from /usr/local/bundle/bin/puma:14:in `<main>'
db_1       | Initializing database
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] /usr/sbin/mysqld (mysqld 10.1.16-MariaDB-1~jessie) starting as process 72 ...
portus_registry_1 exited with code 126
portus_web_1 exited with code 1
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: The InnoDB memory heap is disabled
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Memory barrier is not used
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Using Linux native AIO
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Using SSE crc32 instructions
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Completed initialization of buffer pool
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: The first specified data file ./ibdata1 did not exist: a new database to be created!
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Setting file ./ibdata1 size to 12 MB
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Database physically writes the file full: wait...
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Setting log file ./ib_logfile101 size to 48 MB
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Setting log file ./ib_logfile1 size to 48 MB
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile0
db_1       | 2016-08-16  2:23:20 140126009673664 [Warning] InnoDB: New log files created, LSN=45883
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Doublewrite buffer not found: creating new
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Doublewrite buffer created
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: 128 rollback segment(s) are active.
db_1       | 2016-08-16  2:23:20 140126009673664 [Warning] InnoDB: Creating foreign key constraint system tables.
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Foreign key constraint system tables created
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Creating tablespace and datafile system tables.
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Tablespace and datafile system tables created.
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB: Waiting for purge to start
db_1       | 2016-08-16  2:23:20 140126009673664 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.30-76.3 started; log sequence number 0
db_1       | 2016-08-16  2:23:20 140125216438016 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] /usr/sbin/mysqld (mysqld 10.1.16-MariaDB-1~jessie) starting as process 100 ...
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: The InnoDB memory heap is disabled
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Memory barrier is not used
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Using Linux native AIO
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Using SSE crc32 instructions
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Completed initialization of buffer pool
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Highest supported file format is Barracuda.
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: 128 rollback segment(s) are active.
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB: Waiting for purge to start
db_1       | 2016-08-16  2:23:23 140420458301376 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.30-76.3 started; log sequence number 1616799
db_1       | 2016-08-16  2:23:23 140419677521664 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1       | 2016-08-16  2:23:25 139976485644224 [Note] /usr/sbin/mysqld (mysqld 10.1.16-MariaDB-1~jessie) starting as process 129 ...
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: The InnoDB memory heap is disabled
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Memory barrier is not used
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Using Linux native AIO
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Using SSE crc32 instructions
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Completed initialization of buffer pool
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Highest supported file format is Barracuda.
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: 128 rollback segment(s) are active.
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB: Waiting for purge to start
db_1       | 2016-08-16  2:23:26 139976485644224 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.30-76.3 started; log sequence number 1616809
db_1       | 2016-08-16  2:23:26 139975706248960 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1       | ERROR: 1049  Unknown database 'test'
db_1       | 2016-08-16  2:23:26 139976485644224 [ERROR] Aborting
db_1       | WARNING: OPENGIS REQUIRED SP-S WERE NOT COMPLETELY INSTALLED!
db_1       | GIS extentions might not work properly.
db_1       | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
db_1       | To do so, start the server, then issue the following commands:
db_1       | '/usr/bin/mysqladmin' -u root password 'new-password'
db_1       | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
db_1       | Alternatively you can run:
db_1       | '/usr/bin/mysql_secure_installation'
db_1       | which will also give you the option of removing the test
db_1       | databases and anonymous user created by default.  This is
db_1       | strongly recommended for production servers.
db_1       | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
db_1       | MySQL manual for more instructions.
db_1       | Please report any problems at http://mariadb.org/jira
db_1       | The latest information about MariaDB is available at http://mariadb.org/.
db_1       | You can find additional information about the MySQL part at:
db_1       | http://dev.mysql.com
db_1       | Support MariaDB development by buying support/new features from MariaDB
db_1       | Corporation Ab. You can contact us about this at sales@mariadb.com.
db_1       | Alternatively consider joining our community based development effort:
db_1       | http://mariadb.com/kb/en/contributing-to-the-mariadb-project/
db_1       | Database initialized
db_1       | MySQL init process in progress...
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] mysqld (mysqld 10.1.16-MariaDB-1~jessie) starting as process 156 ...
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: The InnoDB memory heap is disabled
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Memory barrier is not used
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Using Linux native AIO
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Using SSE crc32 instructions
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Completed initialization of buffer pool
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Highest supported file format is Barracuda.
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: 128 rollback segment(s) are active.
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB: Waiting for purge to start
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.30-76.3 started; log sequence number 1616819
db_1       | 2016-08-16  2:23:28 140321786660608 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] Plugin 'FEEDBACK' is disabled.
db_1       | 2016-08-16  2:23:28 140322564011968 [Warning] 'user' entry 'root@b416162fc48d' ignored in --skip-name-resolve mode.
db_1       | 2016-08-16  2:23:28 140322564011968 [Warning] 'proxies_priv' entry '@% root@b416162fc48d' ignored in --skip-name-resolve mode.
db_1       | 2016-08-16  2:23:28 140322564011968 [Note] mysqld: ready for connections.
db_1       | Version: '10.1.16-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
db_1       | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1       | 2016-08-16  2:23:30 140322563533568 [Warning] 'proxies_priv' entry '@% root@b416162fc48d' ignored in --skip-name-resolve mode.
db_1       | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1       | 2016-08-16  2:23:30 140322563230464 [Note] mysqld: Normal shutdown
db_1       | 2016-08-16  2:23:30 140322563230464 [Note] Event Scheduler: Purging the queue. 0 events
db_1       | 2016-08-16  2:23:30 140321769875200 [Note] InnoDB: FTS optimize thread exiting.
db_1       | 2016-08-16  2:23:30 140322563230464 [Note] InnoDB: Starting shutdown...
db_1       | 2016-08-16  2:23:32 140322563230464 [Note] InnoDB: Shutdown completed; log sequence number 1616829
db_1       | 2016-08-16  2:23:32 140322563230464 [Note] mysqld: Shutdown complete
db_1       | MySQL init process done. Ready for start up.
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] mysqld (mysqld 10.1.16-MariaDB-1~jessie) starting as process 1 ...
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Using mutexes to ref count buffer pool pages
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: The InnoDB memory heap is disabled
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Memory barrier is not used
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Using Linux native AIO
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Using SSE crc32 instructions
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Initializing buffer pool, size = 256.0M
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Completed initialization of buffer pool
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Highest supported file format is Barracuda.
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: 128 rollback segment(s) are active.
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB: Waiting for purge to start
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.30-76.3 started; log sequence number 1616829
db_1       | 2016-08-16  2:23:33 139938871871232 [Note] InnoDB: Dumping buffer pool(s) not yet started
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] Plugin 'FEEDBACK' is disabled.
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] Server socket created on IP: '::'.
db_1       | 2016-08-16  2:23:33 139939651352512 [Warning] 'proxies_priv' entry '@% root@b416162fc48d' ignored in --skip-name-resolve mode.
db_1       | 2016-08-16  2:23:33 139939651352512 [Note] mysqld: ready for connections.
db_1       | Version: '10.1.16-MariaDB-1~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
crono_1    | Could not locate Gemfile or .bundle/ directory
portus_crono_1 exited with code 10
```


portus_web cannot start.
Blew is portus_web container's log.

```
[root@registry portus]# docker  logs 204b9241ad6e
/usr/local/bundle/gems/bundler-1.10.4/lib/bundler/definition.rb:23:in `build': /portus/Gemfile not found (Bundler::GemfileNotFound)
        from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler.rb:155:in `definition'
        from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler.rb:123:in `setup'
        from /usr/local/bundle/gems/bundler-1.10.4/lib/bundler/setup.rb:18:in `<top (required)>'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /usr/local/bundle/bin/puma:14:in `<main>'
```

**Comment by monstermunchkin** [comment] 2016-08-16 08:18
Which version of Portus are you running? I cannot reproduce this issue with the master branch nor with v2.0.0. `docker-compose` version 1.6 also doesn't seem to be the issue.

The logs show a missing `Gemfile` which shouldn't be the case as the `Dockerfile` copies this file into the Docker image. This `Gemfile` does exist in your copy of this repository, right?

**Comment by yeruisen** [comment] 2016-08-16 08:36
@monstermunchkin,hello
the version is 2.0.5,
and repository ：

```
root@registry portus]# ls
app               config           deploy              Dockerfile    LICENSE    README.md    vendor
bin               config.ru        doc                 Gemfile       packaging  spec         VERSION
CHANGELOG.md      CONTRIBUTING.md  docker              Gemfile.lock  public     vagrant
compose-setup.sh  db               docker-compose.yml  lib           Rakefile   Vagrantfile
[root@registry portus]#
```

I think it's related to my host environment . Because  when I run on the mac virtualbox ,and docker verson is 1.11.2, compose version is 1.8, install Portus is ok,but when I run on my centos 7.2 ,then docker version is 1.10.3, and compose version is 1.6, install Portus failed.

**Comment by yeruisen** [comment] 2016-08-16 08:46
@monstermunchkin,hello

Can communicate by e-mail? It is more convenient.
My E-mail is yeruisen@sina.cn.

**Comment by yeruisen** [comment] 2016-08-16 09:00
```
[root@registry Portus]# ls
app               config           deploy              Dockerfile    LICENSE    README.md    vendor
bin               config.ru        doc                 Gemfile       packaging  spec         VERSION
CHANGELOG.md      CONTRIBUTING.md  docker              Gemfile.lock  public     vagrant
compose-setup.sh  db               docker-compose.yml  lib           Rakefile   Vagrantfile
[root@registry Portus]# ./compose-setup.sh -e
./compose-setup.sh: 非法选项 -- e
Invalid option: -
Usage: ./compose-setup.sh [-f]
  -f force removal of data
[root@registry Portus]# ./compose-setup.sh -f
The setup will destroy the containers used by Portus, removing also their volumes.
No stopped containers
Creating portus_db_1
Building web
Step 1 : FROM library/rails:4.2.2
 ---> 54b30acf760f
Step 2 : MAINTAINER Flavio Castelli <fcastelli@suse.com>
 ---> Using cache
 ---> 1ae7337e41c3
Step 3 : ENV COMPOSE 1
 ---> Using cache
 ---> 5195bc50ad22
Step 4 : EXPOSE 3000
 ---> Using cache
 ---> dd0b93b0ecc7
Step 5 : WORKDIR /portus
 ---> Using cache
 ---> c94d1deaff1a
Step 6 : COPY Gemfile* ./
 ---> ee8ddae8fefb
Removing intermediate container af9140f4ffc3
Step 7 : RUN bundle install --retry=3
 ---> Running in d1cc7c253d54
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing rake 10.3.2
Using i18n 0.7.0
Using json 1.8.1
Installing minitest 5.7.0
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.2
Using builder 3.2.2
Using erubis 2.7.0
Installing mini_portile 0.5.2
Installing nokogiri 1.6.1 with native extensions
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.6
Using loofah 2.0.2
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.2
Installing rack 1.6.4
Installing rack-test 0.6.2
Using actionpack 4.2.2
Using globalid 0.3.5
Using activejob 4.2.2
Installing mime-types 1.25
```

**Comment by nohtyp** [comment] 2016-08-16 22:32
ok..I was able to get it installed using docker-engine and not the docker supplied with the CentOS-7 repo.  I followed this info to get it working: 

1. https://docs.docker.com/engine/installation/linux/centos/
2. https://docs.docker.com/compose/install/

**Comment by yeruisen** [comment] 2016-08-17 02:37
@nohtyp  ,hello

Thank you for your advice.I followed your advice to get it working..

@monstermunchkin ,hello
The issues is due to the docker-engine version and docker compose version .

**Comment by monstermunchkin** [comment] 2016-08-17 07:37
Thanks for your input, @nohtyp and @yeruisen. I'm closing this issue since the problem you describe is not actually caused by Portus itself.

**Closed by monstermunchkin** 2016-08-17 07:37 UTC
