### ISSUE TITLE
Cannot auth to registry

### ISSUE THREAD

**Issue by huslage** [SUSE/Portus#238] opened 2015-07-30 01:13 UTC
I made this `docker-compose.yml`

```yaml
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: portus
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - "3000:3000"
  links:
    - db
    - reg

reg:
  image: distribution/registry
  ports:
    - "5000:5000"
```

The database is created and migrated, the web server is available on port 3000, the registry is available on port 5000. I added an `admin` user and added the registry as `reg`. I added a team and namespace.

`docker login localhost:5000` returns: 

```
Username: admin
Password: 
Email: a@b.com
Error response from daemon: no successful auth challenge for http://portus_reg_1:5000/v2/ - errors: []
```

It appears that there is zero traffic passing between the registry and portus containers. I can `exec` a shell in `portus_web_1` and ping `reg` just fine, so I don't see where the issue is.

Logs from `portus_reg_1` container:

```
time="2015-07-30T00:54:59.912793031Z" level=info msg="endpoint local-8082 disabled, skipping" environment=development instance.id=a05afaff-52b5-4464-a8c2-39928cdb4469 service=registry version=v2.0.1 
time="2015-07-30T00:54:59.912989277Z" level=info msg="endpoint local-8083 disabled, skipping" environment=development instance.id=a05afaff-52b5-4464-a8c2-39928cdb4469 service=registry version=v2.0.1 
time="2015-07-30T00:54:59.913092613Z" level=info msg="using inmemory layerinfo cache" environment=development instance.id=a05afaff-52b5-4464-a8c2-39928cdb4469 service=registry version=v2.0.1 
time="2015-07-30T00:54:59.913131996Z" level=info msg="listening on :5000" environment=development instance.id=a05afaff-52b5-4464-a8c2-39928cdb4469 service=registry version=v2.0.1 
time="2015-07-30T00:54:59.913289812Z" level=info msg="debug server listening localhost:5001" 
time="2015-07-30T01:03:37.039504866Z" level=debug msg="authorizing request" environment=development http.request.host="localhost:5000" http.request.id=3e623529-492f-4dd2-8e94-7208e3902527 http.request.method=GET http.request.remoteaddr="172.17.42.1:43022" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.19.0-25-generic os/linux arch/amd64" instance.id=a05afaff-52b5-4464-a8c2-39928cdb4469 service=registry version=v2.0.1 
time="2015-07-30T01:03:37.03969024Z" level=info msg="response completed" environment=development http.request.host="localhost:5000" http.request.id=3e623529-492f-4dd2-8e94-7208e3902527 http.request.method=GET http.request.remoteaddr="172.17.42.1:43022" http.request.uri="/v2/" http.request.useragent="docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.19.0-25-generic os/linux arch/amd64" http.response.contenttype="application/json; charset=utf-8" http.response.duration=4.704501ms http.response.status=200 http.response.written=2 instance.id=a05afaff-52b5-4464-a8c2-39928cdb4469 service=registry version=v2.0.1 
172.17.42.1 - - [30/Jul/2015:01:03:37 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.7.1 go/go1.4.2 git-commit/786b29d kernel/3.19.0-25-generic os/linux arch/amd64"
```

Logs from `portus_web_1` container:

```
=> Booting Thin
=> Rails 4.2.2 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3000, CTRL+C to stop


Started GET "/namespaces" for 172.17.42.1 at 2015-07-30 00:57:38 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
  ActiveRecord::SchemaMigration Load (8.3ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by NamespacesController#index as HTML
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
   (0.6ms)  SELECT COUNT(*) FROM `registries`
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
  Namespace Load (2.7ms)  SELECT `namespaces`.* FROM `namespaces` WHERE (global = 1 OR namespaces.name = 'admin')
  Registry Load (0.7ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`id` = 1 LIMIT 1
   (1.4ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 1
  Rendered namespaces/_namespace.html.slim (81.5ms)
   (0.6ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 2
  Rendered namespaces/_namespace.html.slim (3.2ms)
  Namespace Load (3.2ms)  SELECT  DISTINCT `namespaces`.* FROM `namespaces` INNER JOIN `teams` ON `teams`.`id` = `namespaces`.`team_id` INNER JOIN `team_users` ON `team_users`.`team_id` = `teams`.`id` WHERE ((namespaces.public = 1 OR team_users.user_id = 1) AND namespaces.global = 0 AND namespaces.name != 'admin') LIMIT 25 OFFSET 0
   (1.2ms)  SELECT DISTINCT COUNT(DISTINCT `namespaces`.`id`) FROM `namespaces` INNER JOIN `teams` ON `teams`.`id` = `namespaces`.`team_id` INNER JOIN `team_users` ON `team_users`.`team_id` = `teams`.`id` WHERE ((namespaces.public = 1 OR team_users.user_id = 1) AND namespaces.global = 0 AND namespaces.name != 'admin')
  Rendered namespaces/index.html.slim within layouts/application (260.7ms)
  Rendered shared/_header.html.slim (21.0ms)
  Rendered shared/_aside.html.slim (15.9ms)
  CACHE (0.1ms)  SELECT COUNT(*) FROM `registries`
  Rendered shared/_notification.html.slim (16.4ms)
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (40.7ms)
Completed 200 OK in 9855ms (Views: 9740.4ms | ActiveRecord: 28.8ms)


Started GET "/namespaces/1" for 172.17.42.1 at 2015-07-30 01:02:34 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by NamespacesController#show as HTML
  Parameters: {"id"=>"1"}
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
  Namespace Load (0.6ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 1 LIMIT 1
  Registry Load (0.5ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`id` = 1 LIMIT 1
  Repository Load (0.7ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`namespace_id` = 1 LIMIT 25 OFFSET 0
   (0.6ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 1
  Rendered namespaces/show.html.slim within layouts/application (22.8ms)
  Rendered shared/_header.html.slim (1.8ms)
  Rendered shared/_aside.html.slim (1.3ms)
   (0.4ms)  SELECT COUNT(*) FROM `registries`
  Rendered shared/_notification.html.slim (0.2ms)
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (5.1ms)
Completed 200 OK in 271ms (Views: 260.1ms | ActiveRecord: 3.0ms)


Started GET "/namespaces" for 172.17.42.1 at 2015-07-30 01:02:40 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by NamespacesController#index as HTML
  User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
   (0.4ms)  SELECT COUNT(*) FROM `registries`
  CACHE (0.1ms)  SELECT COUNT(*) FROM `registries`
  Namespace Load (0.4ms)  SELECT `namespaces`.* FROM `namespaces` WHERE (global = 1 OR namespaces.name = 'admin')
  Registry Load (0.4ms)  SELECT  `registries`.* FROM `registries` WHERE `registries`.`id` = 1 LIMIT 1
   (0.4ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 1
  Rendered namespaces/_namespace.html.slim (5.4ms)
   (0.4ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 2
  Rendered namespaces/_namespace.html.slim (3.6ms)
  Namespace Load (0.5ms)  SELECT  DISTINCT `namespaces`.* FROM `namespaces` INNER JOIN `teams` ON `teams`.`id` = `namespaces`.`team_id` INNER JOIN `team_users` ON `team_users`.`team_id` = `teams`.`id` WHERE ((namespaces.public = 1 OR team_users.user_id = 1) AND namespaces.global = 0 AND namespaces.name != 'admin') LIMIT 25 OFFSET 0
   (0.7ms)  SELECT DISTINCT COUNT(DISTINCT `namespaces`.`id`) FROM `namespaces` INNER JOIN `teams` ON `teams`.`id` = `namespaces`.`team_id` INNER JOIN `team_users` ON `team_users`.`team_id` = `teams`.`id` WHERE ((namespaces.public = 1 OR team_users.user_id = 1) AND namespaces.global = 0 AND namespaces.name != 'admin')
  Rendered namespaces/index.html.slim within layouts/application (30.5ms)
  Rendered shared/_header.html.slim (1.3ms)
  Rendered shared/_aside.html.slim (0.9ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notification.html.slim (1.1ms)
  Rendered shared/_notifications.html.slim (5.5ms)
Completed 200 OK in 345ms (Views: 333.5ms | ActiveRecord: 3.9ms)


Started POST "/namespaces" for 172.17.42.1 at 2015-07-30 01:02:49 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by NamespacesController#create as JS
  Parameters: {"utf8"=>"✓", "namespace"=>{"namespace"=>"demo", "team"=>"demo"}, "commit"=>"Create"}
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
  Team Load (6.9ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`name` = 'demo' AND `teams`.`hidden` = 0 LIMIT 1
  Rendered namespaces/create.js.erb (1.9ms)
Filter chain halted as :check_team rendered or redirected
Completed 404 Not Found in 32ms (Views: 10.5ms | ActiveRecord: 10.4ms)


Started GET "/teams" for 172.17.42.1 at 2015-07-30 01:02:50 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by TeamsController#index as HTML
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
  Team Load (7.5ms)  SELECT  `teams`.* FROM `teams` INNER JOIN `team_users` ON `teams`.`id` = `team_users`.`team_id` WHERE `team_users`.`user_id` = 1 AND `teams`.`hidden` = 0 LIMIT 25 OFFSET 0
   (0.9ms)  SELECT COUNT(*) FROM `teams` INNER JOIN `team_users` ON `teams`.`id` = `team_users`.`team_id` WHERE `team_users`.`user_id` = 1 AND `teams`.`hidden` = 0
  Rendered teams/index.html.slim within layouts/application (34.7ms)
  Rendered shared/_header.html.slim (1.5ms)
  Rendered shared/_aside.html.slim (1.1ms)
   (0.3ms)  SELECT COUNT(*) FROM `registries`
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (3.9ms)
Completed 200 OK in 298ms (Views: 261.2ms | ActiveRecord: 10.9ms)


Started POST "/teams" for 172.17.42.1 at 2015-07-30 01:02:54 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by TeamsController#create as JS
  Parameters: {"utf8"=>"✓", "team"=>{"name"=>"demo"}, "commit"=>"Add"}
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
   (0.3ms)  BEGIN
  Team Exists (0.6ms)  SELECT  1 AS one FROM `teams` WHERE `teams`.`name` = BINARY 'demo' LIMIT 1
  TeamUser Exists (6.7ms)  SELECT  1 AS one FROM `team_users` WHERE (`team_users`.`user_id` = BINARY 1 AND `team_users`.`team_id` IS NULL) LIMIT 1
  User Exists (1.5ms)  SELECT  1 AS one FROM `users` WHERE (`users`.`username` = BINARY 'admin' AND `users`.`id` != 1) LIMIT 1
  SQL (0.6ms)  INSERT INTO `teams` (`name`, `created_at`, `updated_at`) VALUES ('demo', '2015-07-30 01:02:54', '2015-07-30 01:02:54')
  TeamUser Exists (2.1ms)  SELECT  1 AS one FROM `team_users` WHERE (`team_users`.`user_id` = BINARY 1 AND `team_users`.`team_id` = 3) LIMIT 1
  SQL (0.5ms)  INSERT INTO `team_users` (`role`, `user_id`, `team_id`, `created_at`, `updated_at`) VALUES (2, 1, 3, '2015-07-30 01:02:54', '2015-07-30 01:02:54')
  TeamUser Exists (1.8ms)  SELECT  1 AS one FROM `team_users` WHERE (`team_users`.`user_id` = BINARY 1 AND `team_users`.`id` != 3 AND `team_users`.`team_id` = 3) LIMIT 1
   (7.4ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (2.8ms)  INSERT INTO `activities` (`owner_id`, `owner_type`, `key`, `trackable_id`, `trackable_type`, `created_at`, `updated_at`) VALUES (1, 'User', 'team.create', 3, 'Team', '2015-07-30 01:02:54', '2015-07-30 01:02:54')
   (7.3ms)  COMMIT
  TeamUser Load (1.1ms)  SELECT  `team_users`.* FROM `team_users` WHERE `team_users`.`team_id` = 3 AND `team_users`.`user_id` = 1 LIMIT 1
   (1.1ms)  SELECT COUNT(*) FROM `users` INNER JOIN `team_users` ON `users`.`id` = `team_users`.`user_id` WHERE `team_users`.`team_id` = 3
   (1.5ms)  SELECT COUNT(*) FROM `namespaces` WHERE `namespaces`.`team_id` = 3
  Rendered teams/_team.html.slim (29.9ms)
  Rendered teams/create.js.erb (32.8ms)
Completed 200 OK in 193ms (Views: 36.1ms | ActiveRecord: 40.8ms)


Started GET "/teams/3" for 172.17.42.1 at 2015-07-30 01:02:58 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by TeamsController#show as HTML
  Parameters: {"id"=>"3"}
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
  Team Load (0.7ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`id` = 3 LIMIT 1
  TeamUser Load (0.7ms)  SELECT  `team_users`.* FROM `team_users` WHERE `team_users`.`team_id` = 3 LIMIT 10 OFFSET 0
  User Load (0.7ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  Rendered team_users/_team_user.html.slim (19.1ms)
   (0.6ms)  SELECT COUNT(*) FROM `team_users` WHERE `team_users`.`team_id` = 3
   (0.4ms)  SELECT COUNT(*) FROM `registries`
  Namespace Load (1.2ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`team_id` = 3 LIMIT 15 OFFSET 0
   (0.3ms)  SELECT COUNT(*) FROM `namespaces` WHERE `namespaces`.`team_id` = 3
  Rendered teams/show.html.slim within layouts/application (94.5ms)
  Rendered shared/_header.html.slim (10.0ms)
  Rendered shared/_aside.html.slim (10.2ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
  Rendered shared/_notification.html.slim (15.0ms)
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (31.7ms)
Completed 200 OK in 365ms (Views: 349.2ms | ActiveRecord: 5.0ms)


Started POST "/namespaces" for 172.17.42.1 at 2015-07-30 01:03:03 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by NamespacesController#create as JS
  Parameters: {"utf8"=>"✓", "namespace"=>{"team"=>"demo", "namespace"=>"dedmo"}, "commit"=>"Add"}
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
  Team Load (0.6ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`name` = 'demo' AND `teams`.`hidden` = 0 LIMIT 1
  Registry Load (0.6ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1
   (0.3ms)  BEGIN
  Namespace Exists (7.1ms)  SELECT  1 AS one FROM `namespaces` WHERE (`namespaces`.`name` = BINARY 'dedmo' AND `namespaces`.`registry_id` = 1) LIMIT 1
  SQL (2.7ms)  INSERT INTO `namespaces` (`team_id`, `name`, `registry_id`, `created_at`, `updated_at`) VALUES (3, 'dedmo', 1, '2015-07-30 01:03:03', '2015-07-30 01:03:03')
   (7.8ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (0.6ms)  INSERT INTO `activities` (`owner_id`, `owner_type`, `key`, `trackable_id`, `trackable_type`, `created_at`, `updated_at`) VALUES (1, 'User', 'namespace.create', 3, 'Namespace', '2015-07-30 01:03:03', '2015-07-30 01:03:03')
   (7.0ms)  COMMIT
   (0.8ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 3
  Rendered namespaces/_namespace.html.slim (12.2ms)
  Namespace Load (1.5ms)  SELECT DISTINCT `namespaces`.* FROM `namespaces` INNER JOIN `teams` ON `teams`.`id` = `namespaces`.`team_id` INNER JOIN `team_users` ON `team_users`.`team_id` = `teams`.`id` WHERE ((namespaces.public = 1 OR team_users.user_id = 1) AND namespaces.global = 0 AND namespaces.name != 'admin')
  CACHE (0.1ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 3  [["namespace_id", 3]]
  Rendered namespaces/_namespace.html.slim (4.2ms)
  Rendered namespaces/create.js.erb (24.8ms)
Completed 200 OK in 88ms (Views: 30.2ms | ActiveRecord: 29.7ms)


Started POST "/namespaces" for 172.17.42.1 at 2015-07-30 01:03:10 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by NamespacesController#create as JS
  Parameters: {"utf8"=>"✓", "namespace"=>{"team"=>"demo", "namespace"=>"demo"}, "commit"=>"Add"}
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
  Team Load (0.3ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`name` = 'demo' AND `teams`.`hidden` = 0 LIMIT 1
  Registry Load (0.3ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1
   (0.3ms)  BEGIN
  Namespace Exists (0.6ms)  SELECT  1 AS one FROM `namespaces` WHERE (`namespaces`.`name` = BINARY 'demo' AND `namespaces`.`registry_id` = 1) LIMIT 1
  SQL (0.6ms)  INSERT INTO `namespaces` (`team_id`, `name`, `registry_id`, `created_at`, `updated_at`) VALUES (3, 'demo', 1, '2015-07-30 01:03:10', '2015-07-30 01:03:10')
   (10.8ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (0.5ms)  INSERT INTO `activities` (`owner_id`, `owner_type`, `key`, `trackable_id`, `trackable_type`, `created_at`, `updated_at`) VALUES (1, 'User', 'namespace.create', 4, 'Namespace', '2015-07-30 01:03:10', '2015-07-30 01:03:10')
   (10.0ms)  COMMIT
   (0.7ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 4
  Rendered namespaces/_namespace.html.slim (3.7ms)
  Namespace Load (2.5ms)  SELECT DISTINCT `namespaces`.* FROM `namespaces` INNER JOIN `teams` ON `teams`.`id` = `namespaces`.`team_id` INNER JOIN `team_users` ON `team_users`.`team_id` = `teams`.`id` WHERE ((namespaces.public = 1 OR team_users.user_id = 1) AND namespaces.global = 0 AND namespaces.name != 'admin')
  CACHE (0.0ms)  SELECT COUNT(*) FROM `repositories` WHERE `repositories`.`namespace_id` = 4  [["namespace_id", 4]]
  Rendered namespaces/_namespace.html.slim (2.1ms)
  Rendered namespaces/create.js.erb (13.9ms)
Completed 200 OK in 62ms (Views: 17.6ms | ActiveRecord: 27.2ms)


Started GET "/admin/dashboard" for 172.17.42.1 at 2015-07-30 01:04:10 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Admin::DashboardController#index as HTML
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
   (0.3ms)  SELECT COUNT(*) FROM `registries`
   (0.5ms)  SELECT COUNT(*) FROM `users`
   (0.5ms)  SELECT COUNT(*) FROM `teams` WHERE `teams`.`hidden` = 0
   (0.5ms)  SELECT COUNT(*) FROM `namespaces`
   (0.7ms)  SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM `activities` LIMIT 20) subquery_for_count
  PublicActivity::Activity Load (0.7ms)  SELECT  `activities`.* FROM `activities`  ORDER BY created_at DESC LIMIT 20
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
  Namespace Load (0.6ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 4 LIMIT 1
  Team Load (0.3ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`id` = 3 LIMIT 1
  Rendered public_activity/namespace/_create.html.slim (17.0ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1  [["id", 1]]
  Namespace Load (0.7ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 3 LIMIT 1
  CACHE (0.0ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`id` = 3 LIMIT 1  [["id", 3]]
  Rendered public_activity/namespace/_create.html.slim (7.4ms)
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1  [["id", 1]]
  CACHE (0.0ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`id` = 3 LIMIT 1  [["id", 3]]
  Rendered public_activity/team/_create.html.slim (10.2ms)
  Rendered admin/dashboard/index.html.slim within layouts/application (68.7ms)
  Rendered shared/_header.html.slim (1.5ms)
  Rendered shared/_aside.html.slim (1.5ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (4.1ms)
Completed 200 OK in 312ms (Views: 302.7ms | ActiveRecord: 5.6ms)


Started GET "/admin/registries" for 172.17.42.1 at 2015-07-30 01:04:15 +0000
Cannot render console from 172.17.42.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Admin::RegistriesController#index as HTML
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
   (0.3ms)  SELECT COUNT(*) FROM `registries`
  Registry Load (0.5ms)  SELECT `registries`.* FROM `registries`
  Rendered admin/registries/index.html.slim within layouts/application (14.2ms)
  Rendered shared/_header.html.slim (1.9ms)
  Rendered shared/_aside.html.slim (1.1ms)
  CACHE (0.0ms)  SELECT COUNT(*) FROM `registries`
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (4.5ms)
Completed 200 OK in 301ms (Views: 296.3ms | ActiveRecord: 1.1ms)
```

**Comment by rtrauntvein** [comment] 2015-07-30 01:22
See #217 for some questions I had regarding adding a registry to the docker-compose setup

I think there is a little bit of direction needed from @flavio and the team

**Comment by huslage** [comment] 2015-07-30 01:28
I can push to the registry container just fine. I just want to play with Portus. I don't need a prod env right now.

**Comment by lsamayoa** [comment] 2015-07-30 11:35
@huslage correct me if I am wrong but the daemon also talks to the authentication service directly that is why it will not be able to find the `portus_reg_1` since it is not inside your `/etc/hosts` but inside the container's

**Comment by flavio** [comment] 2015-07-30 12:15
@lsamayoa yes this is correct. I'm currently working a solution for that

**Comment by lsamayoa** [comment] 2015-07-30 14:28
@flavio I don't think that there is any other solution than manually modify the file in the host machine

**Comment by flavio** [comment] 2015-07-30 17:14
Closing as duplicate of https://github.com/SUSE/Portus/issues/217

**Closed by flavio** 2015-07-30 17:14 UTC

**Comment by flavio** [comment] 2015-07-30 17:17
For @huslage: take a look at this PR: https://github.com/SUSE/Portus/pull/239
