### ISSUE TITLE
`docker-compose up` currently failing

### ISSUE THREAD

**Issue by vbatts** [SUSE/Portus#1501] opened 2017-11-02 13:58 UTC
Versions:
portus HEAD of 2cd73bbc666e2c321360341ac888ad594c0d212a
Docker version 1.13.1, build b5e3294/1.13.1

Last of the output of `docker-compose up -d`:
```
[...]
(63/77) Installing: libpolkit0-0.113-13.1.x86_64 [......done]
(64/77) Installing: polkit-0.113-13.1.x86_64 [.........done]
Additional rpm output:
Failed to connect to bus: No such file or directory


(65/77) Installing: polkit-default-privs-13.2-17.1.noarch [.....done]
Additional rpm output:
Updating /etc/sysconfig/security...


(66/77) Installing: libasan0-4.8.5-26.2.x86_64 [......done]
(67/77) Installing: ncurses-utils-5.9-59.1.x86_64 [.........done]
(68/77) Installing: systemd-sysvinit-228-35.1.x86_64 [.........done]
(69/77) Installing: tcsh-6.18.01-11.1.x86_64 [..........done]
(70/77) Installing: cpp48-4.8.5-26.2.x86_64 [............done]
(71/77) Installing: cvs-1.12.12-188.1.x86_64 [...........done]
(72/77) Installing: gcc48-4.8.5-26.2.x86_64 [............done]
(73/77) Installing: aaa_base-13.2+git20140911.61c1681-27.2.x86_64 [..........done]
Additional rpm output:
Updating /etc/sysconfig/language...
Updating /etc/sysconfig/backup...
Updating /etc/sysconfig/proxy...
Updating /etc/sysconfig/windowmanager...
Updating /etc/sysconfig/news...
Updating etc/passwd...unchanged
Updating etc/group...unchanged
Updating etc/shadow...unchanged


(74/77) Installing: cpp-4.8-11.16.x86_64 [......done]
(75/77) Installing: patterns-openSUSE-base-20170518-6.1.x86_64 [.....done]
(76/77) Installing: gcc-4.8-11.16.x86_64 [.........done]
(77/77) Installing: patterns-openSUSE-devel_basis-20170518-6.1.x86_64 [.....done]
Output of kbd-2.0.3-3.14.x86_64.rpm %posttrans script:
    Please run mkinitrd as soon as your system is complete.

Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Your Ruby version is 2.4.1, but your Gemfile specified >= 2.4
ERROR: Service 'portus' failed to build: The command '/bin/sh -c zypper ref &&     zypper -n in --no-recommends ruby2.4-devel ruby2.4-rubygem-bundler            libxml2-devel nodejs libmysqlclient-devel postgresql-devel libxslt1 &&     zypper -n in --no-recommends -t pattern devel_basis &&     bundle install --retry=3 &&     zypper -n rm wicked wicked-service autoconf automake            binutils bison cpp cvs flex gdbm-devel gettext-tools            libtool m4 make makeinfo &&     zypper clean -a' returned a non-zero code: 18

```

**Comment by Vad1mo** [comment] 2017-11-02 14:05
duplicate of #1498

**Comment by mssola** [comment] 2017-11-02 14:40
> duplicate of #1498

Certainly 👍

**Comment by vbatts** [comment] 2017-11-02 15:00
oh nice. I scrolled through the issues and didn't notice it.
Thanks!

**Closed** 2017-11-09 19:30 UTC
Labels: bug, container, duplicate
