### ISSUE TITLE
LDAP users with . in their name unable to log in 

### ISSUE THREAD

**Issue by cpoole** [SUSE/Portus#969] opened 2016-07-08 19:48 UTC
just upgraded portus from commit 89da1fb to HEAD (master branch). LDAP auth is still enabled but now when I attempt to log in I get the following error: 

```
portus_2       | 2016-07-08T19:39:53.590107452Z Started POST "/users/sign_in" for 10.42.111.10 at 2016-07-08 19:39:53 +0000
portus_2       | 2016-07-08T19:39:53.591834174Z Processing by Auth::SessionsController#create as HTML
portus_2       | 2016-07-08T19:39:53.591943949Z   Parameters: {"utf8"=>"✓", "authenticity_token"=>"bMIsFNt8gcboBqay0CBCJXpShr0nRnkgvSW+jNKuLG4bbDog/miBeP6BGTS/wbxrHpZbSWi7u4kDO1uAnAHn+A==", "user"=>{"username"=>"connor.poole", "password"=>"[FILTERED]"}, "button"=>""}
portus_2       | 2016-07-08T19:39:55.456462473Z   User Load (1.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`username` = 'connor.poole' LIMIT 1
portus_2       | 2016-07-08T19:39:56.429724750Z    (1.0ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus')
portus_2       | 2016-07-08T19:39:56.573627266Z    (0.7ms)  BEGIN
portus_2       | 2016-07-08T19:39:56.584487291Z   User Exists (1.3ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'connor.poole@SOMETHING.com' LIMIT 1
portus_2       | 2016-07-08T19:39:56.586656971Z   User Exists (0.7ms)  SELECT  1 AS one FROM `users` WHERE `users`.`username` = BINARY 'connor.poole' LIMIT 1
portus_2       | 2016-07-08T19:39:56.588215777Z   Namespace Exists (0.6ms)  SELECT  1 AS one FROM `namespaces` WHERE `namespaces`.`name` = 'connor.poole' LIMIT 1
portus_2       | 2016-07-08T19:39:56.589566778Z   Team Exists (0.6ms)  SELECT  1 AS one FROM `teams` WHERE `teams`.`name` = 'connor.poole' LIMIT 1
portus_2       | 2016-07-08T19:39:56.590544496Z    (0.5ms)  ROLLBACK
portus_2       | 2016-07-08T19:39:56.592389591Z   User Exists (0.6ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'connor.poole@SOMETHING.com' LIMIT 1
portus_2       | 2016-07-08T19:39:56.594283563Z   User Exists (0.6ms)  SELECT  1 AS one FROM `users` WHERE `users`.`username` = BINARY 'connor.poole' LIMIT 1
portus_2       | 2016-07-08T19:39:56.595569121Z   Namespace Exists (0.6ms)  SELECT  1 AS one FROM `namespaces` WHERE `namespaces`.`name` = 'connor.poole' LIMIT 1
portus_2       | 2016-07-08T19:39:56.597630471Z   Team Exists (1.4ms)  SELECT  1 AS one FROM `teams` WHERE `teams`.`name` = 'connor.poole' LIMIT 1
portus_2       | 2016-07-08T19:39:56.598791014Z Completed 401 Unauthorized in 3007ms (ActiveRecord: 9.9ms)
```

on the front end I get a popup that says this email has already been selected.
[http://imgur.com/by1kJQa](url)
if I look in the database my username is shown as connorpoole (note this lacks the . )

Now if I update my username:

```
mysql> UPDATE users
    -> SET username='connor.poole'
    -> WHERE username='connorpoole';
```

suggestions? is this a new feature I have inadvertently enabled?

Thanks,
Connor

**Comment by cpoole** [comment] 2016-07-08 22:23
ah I appear to be caught in some mid-schema migration strangeness between https://github.com/SUSE/Portus/pull/904 and https://github.com/SUSE/Portus/issues/922

Am I interpreting this correctly? is the long term goal to have the username = the current ldap_name field? and then introduce a stripped version that complies with docker for the namespace_id field?

Do you need any help writing these DB migrations?

**Comment by mssola** [comment] 2016-07-11 08:46
@cpoole as you are saying, we changed the way we handle user names. Now, there will be no translations between user names and an LDAP name, because we are not directly mapping them into namespaces. Instead, the users table now has a `namespace_id` foreign key that does the right thing (resulting namespaces with an invalid namespace name will still be translated into valid ones). Furthermore, we introduced the `portus:update_personal_namespaces` rake task for the migration of the old format to the new one.

But maybe we are missing that for old versions the `ldap_name` contained the right name as used in LDAP. So, I will add another rake task that will basically do this (ldap_name -> username). What do you think ?

**Comment by mssola** [comment] 2016-07-11 15:02
Now that #971 has been merged, could you try it out and tell me whether it fixes your problems ? Note that what the task is basically doing is:

- Present to you users with an non-blank `ldap_name` that does not match the `username`.
- If you accept, then for those users the `username` will have the same value as `ldap_name`.

**Comment by cpoole** [comment] 2016-07-11 21:21
Hey @mssola sorry for the late response, the time difference out here in California makes this tough hah.

I went ahead and rebuilt my containers off of latest master started them up, ran `rake portus:update_personal_namespaces` and got the following:

```
rake portus:update_personal_namespaces
[Mailer config] Host:     portus.something.info
[Mailer config] Protocol: https://
  ActiveRecord::SchemaMigration Load (0.7ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
   (0.8ms)  BEGIN
  User Load (0.8ms)  SELECT  `users`.* FROM `users`  ORDER BY `users`.`id` ASC LIMIT 1000
  Namespace Load (0.8ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`name` = 'portus' LIMIT 1
  User Exists (0.8ms)  SELECT  1 AS one FROM `users` WHERE (`users`.`username` = BINARY 'portus' AND `users`.`id` != 1) LIMIT 1
  SQL (0.8ms)  UPDATE `users` SET `namespace_id` = 2, `updated_at` = '2016-07-11 20:59:48' WHERE `users`.`id` = 1
  Namespace Load (0.7ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`name` = 'connor.poole' LIMIT 1
   (3.8ms)  ROLLBACK
rake aborted!
There is no valid personal namespace for connor.poole!
/portus/lib/tasks/portus.rake:144:in `block (4 levels) in <top (required)>'
/portus/lib/tasks/portus.rake:142:in `block (3 levels) in <top (required)>'
/portus/lib/tasks/portus.rake:141:in `block (2 levels) in <top (required)>'
```

same issue when I run `rake portus:update_personal_namespaces`

I think I missed some schema migration for a point release. the `namespace_id` column is NULL for all users. 

I'll dig through the docs and try and fix this first.

**Comment by cpoole** [comment] 2016-07-12 00:51
Also @mssola I opened a pull request to add an env var override for this rake task. https://github.com/SUSE/Portus/pull/973 

Do you have a master list somewhere in the docs where all possible env vars are listed?

**Comment by mssola** [comment] 2016-07-12 15:11
I think that you should've executed `portus:update_personal_namespaces` before calling `portus:update_ldap_names`. This is because `portus:update_personal_namespaces` relies on the fact that namespaces and usernames map 1-to-1 (old way of handling this). And only then you can execute the other rake task. I should probably come up with a rake task that does this, to avoid confusion to other users. Sorry about that, should've told you that the order matters :sweat: 

Now, what you can do is to rollback to the previous DB state and perform these two tasks in the right order, or you would have to update things manually (e.g. by updating the namespace_id with the one that corresponds to users with dots and other characters that are not allowed in namespaces).

Sorry for the inconvenience (the "perks" of living in the master branch I guess :sweat_smile:). We will try to release more often as of the next stable version, so less people are trapped on migrations happening on a commit basis.

**Comment by cpoole** [comment] 2016-07-13 00:08
hey @mssola I actually did run `portus:update_personal_namespaces` before running `portus:update_ldap_names` and it failed with the same error. 

I think this is because on lines 141-146 in the `/lib/tasks/portus.rake` there is a throw if namespace = nil.
```
    ActiveRecord::Base.transaction do
      User.all.find_each do |u|
        namespace = Namespace.find_by(name: u.username)
        raise "There is no valid personal namespace for #{u.username}!" if namespace.nil?
        u.update_attributes(namespace: namespace)
      end
    end
```

and somehow in my database the namespace_id column in the users table is all `NULL`

I think somewhere I missed a migration script or a rake task between 89da1fb and current HEAD. any guess as to why would be much appreciated.

I really like Portus so no need to apologize for the master branch. I'm happy to help test and help sort out bugs.

**Comment by cpoole** [comment] 2016-07-13 00:32
this might help. I removed most sensitive info
```
mysql> select * from users;
+----+------------------+----------------------------+----------------------+----------------------+------------------------+---------------------+---------------+---------------------+---------------------+--------------------+-----------------+---------------------+---------------------+-------+---------+------------------+-----------------+-----------+--------------+--------------+
| id | username         | email                      | encrypted_password   | reset_password_token | reset_password_sent_at | remember_created_at | sign_in_count | current_sign_in_at  | last_sign_in_at     | current_sign_in_ip | last_sign_in_ip | created_at          | updated_at          | admin | enabled | ldap_name        | failed_attempts | locked_at | namespace_id | display_name |
+----+------------------+----------------------------+----------------------+----------------------+------------------------+---------------------+---------------+---------------------+---------------------+--------------------+-----------------+---------------------+---------------------+-------+---------+------------------+-----------------+-----------+--------------+--------------+
|  1 | portus           | portus@portus.com          | lol, no              | NULL                 | NULL                   | NULL                |            16 | 2016-07-11 22:55:54 | 2016-07-11 22:55:51 | probably not       | meh.            | 2016-05-12 21:28:55 | 2016-07-11 22:55:54 |     1 |       1 | NULL             |               0 | NULL      |         NULL | NULL         |
|  2 | connor.poole     | connor.poole@some.com      | lol, no              | NULL                 | NULL                   | NULL                |           160 | 2016-07-11 22:55:53 | 2016-07-11 22:55:50 | probably not       | meh.            | 2016-05-12 21:29:38 | 2016-07-11 22:55:53 |     1 |       1 | connor.poole     |               0 | NULL      |         NULL | NULL         |
|  3 | nope             | definitely not             | lol, no              | NULL                 | NULL                   | NULL                |             3 | 2016-06-15 21:21:14 | 2016-05-12 22:11:11 | probably not       | meh.            | 2016-05-12 22:11:10 | 2016-07-11 23:54:43 |     0 |       1 | nope             |               0 | NULL      |         NULL | NULL         |
|  4 | nope             | definitely not             | lol, no              | NULL                 | NULL                   | NULL                |             1 | 2016-05-13 00:23:03 | 2016-05-13 00:23:03 | probably not       | meh.            | 2016-05-13 00:23:03 | 2016-07-11 23:54:43 |     0 |       1 | nope             |               0 | NULL      |         NULL | NULL         |
|  5 | nope             | definitely not             | lol, no              | NULL                 | NULL                   | NULL                |             4 | 2016-05-13 17:38:54 | 2016-05-13 17:38:38 | probably not       | meh.            | 2016-05-13 01:19:32 | 2016-07-11 23:54:43 |     0 |       1 | nope             |               0 | NULL      |         NULL | NULL         |
|  6 | nope             | definitely not             | lol, no              | NULL                 | NULL                   | NULL                |             1 | 2016-05-27 20:37:26 | 2016-05-27 20:37:26 | probably not       | meh.            | 2016-05-27 20:37:26 | 2016-07-11 23:54:43 |     0 |       1 | nope             |               0 | NULL      |         NULL | NULL         |
|  7 | nope             | definitely not             | lol, no              | NULL                 | NULL                   | NULL                |             1 | 2016-06-09 00:34:46 | 2016-06-09 00:34:46 | probably not       | meh.            | 2016-06-09 00:34:46 | 2016-07-11 23:54:43 |     0 |       1 | nope             |               0 | NULL      |         NULL | NULL         |
|  8 | nope             | definitely not             | lol, no              | NULL                 | NULL                   | NULL                |            33 | 2016-07-11 22:56:14 | 2016-07-11 22:56:12 | probably not       | meh.            | 2016-06-13 21:53:31 | 2016-07-11 22:56:14 |     0 |       1 | nope             |               0 | NULL      |         NULL | NULL         |
|  9 | nope             | definitely not             | lol, no              | NULL                 | NULL                   | NULL                |             6 | 2016-06-15 23:13:40 | 2016-06-15 23:10:32 | probably not       | meh.            | 2016-06-15 21:47:26 | 2016-07-11 23:54:43 |     0 |       1 | nope             |               0 | NULL      |         NULL | NULL         |
| 10 | nope             | definitely not             | lol, no              | NULL                 | NULL                   | NULL                |             3 | 2016-07-08 19:33:33 | 2016-06-29 23:37:35 | probably not       | meh.            | 2016-06-29 23:32:24 | 2016-07-08 19:33:33 |     0 |       1 | nope             |               0 | NULL      |         NULL | NULL         |
+----+------------------+----------------------------+----------------------+----------------------+------------------------+---------------------+---------------+---------------------+---------------------+--------------------+-----------------+---------------------+---------------------+-------+---------+------------------+-----------------+-----------+--------------+--------------+
```

**Comment by mssola** [comment] 2016-07-14 15:31
This is really weird indeed :confused:. The code you posted should never fail because before the change, users had the same value for username and their personal  namespace. That's why I thought that you ran `portus:update_ldap_names` before the other one.

I've tested this again and added a test in #986. Would it be possible for you to try to reproduce this from scratch ?

**Comment by cpoole** [comment] 2016-07-14 18:21
Sure I can test again with a fresh DB. 

Do you want me to follow this flow:
- start fresh from 89da1fb 
- create a few users
- upgrade to HEAD
- run `portus:update_personal_namespaces` and `portus:update_ldap_names`

That would test the upgrade from april to now (the VERSION file for both is 2.1.0-dev).

Or would you prefer I:
- start fresh from HEAD
- create a few users
- run `portus:update_personal_namespaces` and `portus:update_ldap_names`

**Comment by mssola** [comment] 2016-07-15 10:12
Both options sound good to me. Maybe the first is the one more error-prone, and thus better to test ? Thanks!

**Comment by mssola** [comment] 2017-10-26 09:24
Closing this since no further action has been done. I can confirm that this issue is not reproducible in master.

**Closed by mssola** 2017-10-26 09:24 UTC
Labels: needs info
