### ISSUE TITLE
example docker-compose up fails

### ISSUE THREAD

**Issue by lukeshaughnessy** [SUSE/Portus#1313] opened 2017-07-10 10:18 UTC
docker-compose pull
Pulling webpack (kkarczmarczyk/node-yarn:6.9-slim)...
6.9-slim: Pulling from kkarczmarczyk/node-yarn
Digest: sha256:2cba65bac826d393b77b72a84b0f8c92ac344890157e722e83d1a2af7868624a
Status: Image is up to date for kkarczmarczyk/node-yarn:6.9-slim
Pulling db (library/mariadb:10.0.23)...
10.0.23: Pulling from library/mariadb
7268d8f794c4: Already exists

Digest: sha256:508d6866998ce604ca0a9560da342baf3c67e613372c1431397b12d7d7a59c47
Status: Image is up to date for mariadb:10.0.23
Pulling crono (portus_portus:latest)...
ERROR: repository portus_portus not found: does not exist or no pull access

**Comment by lukeshaughnessy** [comment] 2017-07-10 11:24
I seem to have gotten past the missing registry error, but now there is this error at the login screen:

Showing /srv/Portus/app/views/layouts/authentication.html.slim where line #6 raised:

Could not load compiled manifest from /srv/Portus/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /srv/Portus/public/assets/webpack/manifest.json)

**Comment by mssola** [comment] 2017-07-11 07:45
That's weird... Just to check, I downloaded the latest `docker-compose` version, and performed the `pull` command. It effectively complains about the missing image. So, it means that you have to build first the `portus_portus` one, which is the one for development purposes built locally, and then pull. Funnily enough, this is all handled automatically with the `up` command. So, with a simple `docker-compose up` it's all performed accordingly and it works.

I've tried adding some `depends_on` and actually tagging the development image but the `pull` command seems to ignore locally built images. So, unless you have a solution, I think you best bet is to simple `docker-compose up`.

> Showing /srv/Portus/app/views/layouts/authentication.html.slim where line #6 raised:
>
> Could not load compiled manifest from /srv/Portus/public/assets/webpack/manifest.json - have you run rake webpack:compile? (original error No such file or directory @ rb_sysopen - /srv/Portus/public/assets/webpack/manifest.json)

I cannot reproduce this. Are you using the latest code from master ? What does the `webpack` container log ?

**Comment by lukeshaughnessy** [comment] 2017-07-11 10:11
I tried again with a totally fresh setup on my mac with the latest docker and docker-compose version and got the following:

```
$ git clone https://github.com/SUSE/Portus.git
Cloning into 'Portus'...

$ git status
On branch master

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

$ docker -v
Docker version 17.06.0-ce, build 02c1d87

$ docker-compose -v
docker-compose version 1.14.0, build c7bdf9e 

$ cd Portus
$ docker-compose up

Pulling webpack (kkarczmarczyk/node-yarn:6.9-slim)...
6.9-slim: Pulling from kkarczmarczyk/node-yarn
<snip>
Digest: sha256:2cba65bac826d393b77b72a84b0f8c92ac344890157e722e83d1a2af7868624a
Status: Downloaded newer image for kkarczmarczyk/node-yarn:6.9-slim
Pulling db (library/mariadb:10.0.23)...
10.0.23: Pulling from library/mariadb
<snip>
Digest: sha256:508d6866998ce604ca0a9560da342baf3c67e613372c1431397b12d7d7a59c47
Status: Downloaded newer image for mariadb:10.0.23
Pulling crono (portus_portus:latest)...
ERROR: repository portus_portus not found: does not exist or no pull access
```
To be honest I don't know how I got the "portus_portus" image to build before, I was just monkeying with things until I say the image appear.

**Comment by mssola** [comment] 2017-07-11 10:21
> It looks like it is logically looking for a package called portus_portus which does not exist on dockerhub.

For me it builds the image first. I have applied some changes (a depends_on, just to be sure). Tell me if this patch works for you:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 48a5e07a7edb..2452a552c248 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -3,6 +3,7 @@ version: '2'
 services:
   portus:
     build: .
+    image: opensuse/portus:development
     command: bash /srv/Portus/examples/development/compose/init
     environment:
       - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
@@ -20,8 +21,10 @@ services:
       - .:/srv/Portus
 
   crono:
-    image: portus_portus
+    image: opensuse/portus:development
     command: ./bin/crono
+    depends_on:
+      - portus
     environment:
       - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}
 

```

**Comment by lukeshaughnessy** [comment] 2017-07-11 10:38
That fix resolved the issue with the missing image, however the other error is back:
This is the tail of the portus container logs:

```
Started GET "/users/sign_up" for 172.19.0.1 at 2017-07-11 10:31:45 +0000
Cannot render console from 172.19.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Auth::RegistrationsController#new as HTML
   (0.6ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus') AND `users`.`enabled` = 1 AND `users`.`admin` = 1
   (0.2ms)  SELECT COUNT(*) FROM `users` WHERE (`users`.`username` != 'portus')
  Rendered shared/_notification.html.slim (13.0ms)
  Rendered shared/_notification.html.slim (0.1ms)
  Rendered shared/_notifications.html.slim (40.6ms)
  Rendered devise/registrations/new.html.slim within layouts/authentication (215.2ms)
Completed 500 Internal Server Error in 6104ms (ActiveRecord: 1.7ms)

ActionView::Template::Error (Could not load compiled manifest from /srv/Portus/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /srv/Portus/public/assets/webpack/manifest.json)):
    3:   head
    4:     title Portus
    5:     = stylesheet_link_tag 'application', media: 'all'
    6:     = javascript_include_tag(*webpack_asset_paths("application"))
    7:     = csrf_meta_tags
    8:     meta content="width=device-width, initial-scale=1" name="viewport"
    9:     link href="/favicon/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"
  app/views/layouts/authentication.html.slim:6:in `_app_views_layouts_authentication_html_slim___2984895993026483106_47409519874920'
  app/controllers/auth/registrations_controller.rb:16:in `new'


  Rendered /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.8ms)
  Rendered /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.0ms)
  Rendered /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.4ms)
  Rendered /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (25.7ms)
```

Incidentally, there is not a container or image called "webpack":

```
 docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                              NAMES
25a1c5158f97        opensuse/portus:development   "./bin/crono"            8 minutes ago       Up 8 minutes        3000/tcp                           portus_crono_1
2531b828fd9b        registry:2.3.1                "/bin/registry /et..."   8 minutes ago       Up 8 minutes        0.0.0.0:5000-5001->5000-5001/tcp   portus_registry_1
29075bd48d35        opensuse/portus:development   "bash /srv/Portus/..."   8 minutes ago       Up 8 minutes        0.0.0.0:3000->3000/tcp             portus_portus_1
f61d6a1b05bc        mariadb:10.0.23               "/docker-entrypoin..."   8 minutes ago       Up 8 minutes        3306/tcp                           portus_db_1
```

**Comment by mssola** [comment] 2017-07-11 10:48
> That fix resolved the issue with the missing image

Ok I'll submit a PR with that.

Regarding the missing webpack container, have you checked with the `-a` flag ? Maybe the container errored out for some reason 😕

**Comment by lukeshaughnessy** [comment] 2017-07-11 12:23
Looks like it was never created:

```
docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                           PORTS               NAMES
25a1c5158f97        opensuse/portus:development        "./bin/crono"            2 hours ago         Exited (137) About an hour ago                       portus_crono_1
2531b828fd9b        registry:2.3.1                     "/bin/registry /et..."   2 hours ago         Exited (2) About an hour ago                         portus_registry_1
29075bd48d35        opensuse/portus:development        "bash /srv/Portus/..."   2 hours ago         Exited (137) About an hour ago                       portus_portus_1
f95dd023f56c        kkarczmarczyk/node-yarn:6.9-slim   "yarn run webpack"       2 hours ago         Exited (1) 2 hours ago                               portus_webpack_1
f61d6a1b05bc        mariadb:10.0.23                    "/docker-entrypoin..."   2 hours ago         Exited (0) About an hour ago                         portus_db_1
```

**Comment by lukeshaughnessy** [comment] 2017-07-11 12:26
```
yarn run v0.27.5
$ webpack --watch --config config/webpack.js
sh: 1: webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mssola** [comment] 2017-07-11 12:53
@lukeshaughnessy now I was able to reproduce it! This happens when using `docker-compose` for the first time, when the `node_modules` directory hasn't been generated yet.

**Comment by mssola** [comment] 2017-07-11 13:23
@lukeshaughnessy take a look at #1316. This should fix your issue.

**Comment by lukeshaughnessy** [comment] 2017-07-11 13:44
@mssola pulling your fork did the trick - I get the web gui now - cheers!

**Comment by mssola** [comment] 2017-07-11 13:47
@lukeshaughnessy merged into master. Thanks for reporting!

**Closed** 2017-07-11 13:47 UTC
Labels: bug

**Comment by raghavendrachari08** [comment] 2017-08-04 09:30
Still am facing this issue which i cloned master branch , is there any thing extra i need to do other than cloning master branch

**Comment by mssola** [comment] 2017-08-04 10:30
@raghavendrachari08 does this work outside of the container ? As in, try to install yarn and run `yarn install`.  Moreover, does `npm install css-loader@0.28.1` work ?

In principle this looks like a connectivity issue honestly. Is there a way I can reproduce this ?

**Comment by raghavendrachari08** [comment] 2017-08-04 11:04
@mssola yes on docker host am able to run npm install css-loader@0.28.1

`[rkamsali@nila Portus]$ npm install css-loader@0.28.1
/localdisk/rkamsali/Portus
└─┬ css-loader@0.28.1 
  ├─┬ babel-code-frame@6.22.0 
  │ ├─┬ chalk@1.1.3 
  │ │ ├── ansi-styles@2.2.1 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ └── ansi-regex@2.1.1 
  │ │ ├── strip-ansi@3.0.1 
  │ │ └── supports-color@2.0.0 
  │ ├── esutils@2.0.2 
  │ └── js-tokens@3.0.2 
  ├─┬ css-selector-tokenizer@0.7.0 
  │ ├── cssesc@0.1.0 
  │ ├── fastparse@1.1.1 
  │ └─┬ regexpu-core@1.0.0 
  │   ├── regenerate@1.3.2 
  │   ├── regjsgen@0.2.0 
  │   └─┬ regjsparser@0.1.5 
  │     └── jsesc@0.5.0 
  ├─┬ cssnano@3.10.0 
  │ ├─┬ autoprefixer@6.7.7 
  │ │ ├─┬ browserslist@1.7.7 
  │ │ │ └── electron-to-chromium@1.3.17 
  │ │ ├── caniuse-db@1.0.30000710 
  │ │ ├── normalize-range@0.1.2 
  │ │ └── num2fraction@1.2.2 
  │ ├── decamelize@1.2.0 
  │ ├── defined@1.0.0 
  │ ├─┬ has@1.0.1 
  │ │ └── function-bind@1.1.0 
  │ ├─┬ postcss-calc@5.3.1 
  │ │ ├── postcss-message-helpers@2.0.0 
  │ │ └─┬ reduce-css-calc@1.3.0 
  │ │   ├── balanced-match@0.4.2 
  │ │   ├── math-expression-evaluator@1.2.17 
  │ │   └── reduce-function-call@1.0.2 
  │ ├─┬ postcss-colormin@2.2.2 
  │ │ └─┬ colormin@1.1.2 
  │ │   ├─┬ color@0.11.4 
  │ │   │ ├── clone@1.0.2 
  │ │   │ ├─┬ color-convert@1.9.0 
  │ │   │ │ └── color-name@1.1.3 
  │ │   │ └── color-string@0.3.0 
  │ │   └── css-color-names@0.0.4 
  │ ├── postcss-convert-values@2.6.1 
  │ ├── postcss-discard-comments@2.0.4 
  │ ├── postcss-discard-duplicates@2.1.0 
  │ ├── postcss-discard-empty@2.1.0 
  │ ├── postcss-discard-overridden@0.1.1 
  │ ├─┬ postcss-discard-unused@2.2.3 
  │ │ └── uniqs@2.0.0 
  │ ├─┬ postcss-filter-plugins@2.0.2 
  │ │ └─┬ uniqid@4.1.1 
  │ │   └── macaddress@0.2.8 
  │ ├── postcss-merge-idents@2.1.7 
  │ ├── postcss-merge-longhand@2.0.2 
  │ ├─┬ postcss-merge-rules@2.1.2 
  │ │ ├─┬ caniuse-api@1.6.1 
  │ │ │ ├── lodash.memoize@4.1.2 
  │ │ │ └── lodash.uniq@4.5.0 
  │ │ ├─┬ postcss-selector-parser@2.2.3 
  │ │ │ ├── flatten@1.0.2 
  │ │ │ ├── indexes-of@1.0.1 
  │ │ │ └── uniq@1.0.1 
  │ │ └── vendors@1.0.1 
  │ ├── postcss-minify-font-values@1.0.5 
  │ ├── postcss-minify-gradients@1.0.5 
  │ ├─┬ postcss-minify-params@1.2.2 
  │ │ └── alphanum-sort@1.0.2 
  │ ├── postcss-minify-selectors@2.1.1 
  │ ├── postcss-normalize-charset@1.1.1 
  │ ├─┬ postcss-normalize-url@3.0.8 
  │ │ ├── is-absolute-url@2.1.0 
  │ │ └─┬ normalize-url@1.9.1 
  │ │   ├── prepend-http@1.0.4 
  │ │   ├─┬ query-string@4.3.4 
  │ │   │ └── strict-uri-encode@1.1.0 
  │ │   └─┬ sort-keys@1.1.2 
  │ │     └── is-plain-obj@1.1.0 
  │ ├── postcss-ordered-values@2.2.3 
  │ ├── postcss-reduce-idents@2.4.0 
  │ ├── postcss-reduce-initial@1.0.1 
  │ ├── postcss-reduce-transforms@1.0.4 
  │ ├─┬ postcss-svgo@2.1.6 
  │ │ ├─┬ is-svg@2.1.0 
  │ │ │ └── html-comment-regex@1.1.1 
  │ │ └─┬ svgo@0.7.2 
  │ │   ├─┬ coa@1.0.4 
  │ │   │ └── q@1.5.0 
  │ │   ├── colors@1.1.2 
  │ │   ├─┬ csso@2.3.2 
  │ │   │ └── clap@1.2.0 
  │ │   ├─┬ js-yaml@3.7.0 
  │ │   │ ├─┬ argparse@1.0.9 
  │ │   │ │ └── sprintf-js@1.0.3 
  │ │   │ └── esprima@2.7.3 
  │ │   ├─┬ mkdirp@0.5.1 
  │ │   │ └── minimist@0.0.8 
  │ │   ├── sax@1.2.4 
  │ │   └── whet.extend@0.9.9 
  │ ├── postcss-unique-selectors@2.0.2 
  │ └── postcss-zindex@2.2.0 
  ├─┬ loader-utils@1.1.0 
  │ ├── big.js@3.1.3 
  │ ├── emojis-list@2.1.0 
  │ └── json5@0.5.1 
  ├── lodash.camelcase@4.3.0 
  ├── object-assign@4.1.1 
  ├─┬ postcss@5.2.17 
  │ ├── js-base64@2.1.9 
  │ ├── source-map@0.5.6 
  │ └─┬ supports-color@3.2.3 
  │   └── has-flag@1.0.0 
  ├─┬ postcss-modules-extract-imports@1.1.0 
  │ └─┬ postcss@6.0.8 
  │   ├─┬ chalk@2.0.1 
  │   │ └── ansi-styles@3.2.0 
  │   └─┬ supports-color@4.2.1 
  │     └── has-flag@2.0.0 
  ├─┬ postcss-modules-local-by-default@1.2.0 
  │ └─┬ postcss@6.0.8 
  │   ├─┬ chalk@2.0.1 
  │   │ └── ansi-styles@3.2.0 
  │   └─┬ supports-color@4.2.1 
  │     └── has-flag@2.0.0 
  ├─┬ postcss-modules-scope@1.1.0 
  │ └─┬ postcss@6.0.8 
  │   ├─┬ chalk@2.0.1 
  │   │ └── ansi-styles@3.2.0 
  │   └─┬ supports-color@4.2.1 
  │     └── has-flag@2.0.0 
  ├─┬ postcss-modules-values@1.3.0 
  │ ├── icss-replace-symbols@1.1.0 
  │ └─┬ postcss@6.0.8 
  │   ├─┬ chalk@2.0.1 
  │   │ └── ansi-styles@3.2.0 
  │   └─┬ supports-color@4.2.1 
  │     └── has-flag@2.0.0 
  ├── postcss-value-parser@3.3.0 
  └── source-list-map@0.1.8 

`

**Comment by raghavendrachari08** [comment] 2017-08-04 11:06
This is the output when am executing inside container 
`root@70cbcbf05fe7:/srv/Portus# npm install css-loader@0.28.1
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.1
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
[..................] / rollbackFailedOptional: verb npm-session 3bc7dd532a472005
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/css-loader failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443`

**Comment by mssola** [comment] 2017-08-04 11:29
It looks like there is something fishy with your network... Could you check whether you can ping registry.npmjs.org from within a container ? If not, maybe you are using a network feature from docker that might be stopping you from accessing internet ? Or maybe you have a firewall rule that is stopping this request ?

**Comment by raghavendrachari08** [comment] 2017-08-04 11:46
yes , it might be something mess with networking;
Now i tried adding option network_mode: bridge ; it resolved the installation issue.
