### ISSUE TITLE
portus cannot send new password via email

### ISSUE THREAD

**Issue by gitm1993** [SUSE/Portus#1686] opened 2018-02-16 11:30 UTC
Hello,

I have problem configure portus to send forgoten passwords via emal. I tried my own smtp and now i trying gmail smtp. I am able to send email via telnet from server. 

portus is running in docker container. 
portus version - 2.2

my config.yml

---

version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
    delete:
        enabled: true
http:
    addr: :5000
    host: registry.example.com
    tls:
        certificate: /certs/example.com.ssl.chained.crt
        key: /certs/example.com.ssl.key

auth:
  token:
    realm: https://portus.example.com/v2/token
    service: registry.example.com
    issuer: portus.example.com
    rootcertbundle: /certs/example.com.ssl.chained.crt

notifications:
  endpoints:
    - name: portus
      url: https://portus.example.com/v2/webhooks/events
      timeout: 500ms
      threshold: 5
      backoff: 1s

email:
  from: "portus@example.com"
  name: "Portus"
  reply_to: "no-reply@example.com"_
_this section i modified many times, with my own smtp or gmail smtp, different ports (25,587,465)_
smtp:
    enabled: true
    address: "smtp.gmail.com"
    port: 465
    user_name: "example@gmail.com"
    password: "***********"
    domain: "gmail.com"

---

in any case, this appear in  log: 

---

Errno::ECONNREFUSED (Connection refused - connect(2) for "localhost" port 25):
app/controllers/passwords_controller.rb:10:in `create'

---

It is look like my setup in config is ignored, cause portus always try connect to port 25 on localhost.

Thank you for help.

Marek

**Comment by Vad1mo** [comment] 2018-02-16 11:33
you should not post your password on the internet:

**Comment by gitm1993** [comment] 2018-02-16 11:36
@Vad1mo yes, mistake

**Comment by Vad1mo** [comment] 2018-02-16 11:37
I would still recommend to update your question and remove the password. You can still do so

**Comment by Vad1mo** [comment] 2018-02-16 11:40
did you also try `port: 587`?

**Comment by gitm1993** [comment] 2018-02-16 11:41
yes

**Comment by mssola** [comment] 2018-02-16 11:44
@gitm1993 you are running portus 2.2. Why don't you try 2.3 (there are some fixes on this regard) ? Bear in mind that there are some changes in regards to [some environment variables](https://github.com/SUSE/Portus/blob/master/CHANGELOG.md#upgrading). You may also want to check the `examples` directory with some docker-compose examples that are known to work 😉

**Comment by Vad1mo** [comment] 2018-02-16 11:44
it looks like it tries to send via sendmail. thats why localhost:

are you sure that `enabled: true` 

http://port.us.org/docs/Configuring-Portus.html#email-configuration

```
email:
  from: "portus@example.com"
  name: "Portus"
  reply_to: "no-reply@example.com"

  smtp:
    enabled: false
    address: "smtp.example.com"
    port: 587,
    user_name: "username@example.com"
    password: "password"
    domain: "example.com"
```

**Comment by Vad1mo** [comment] 2018-02-16 11:49
As @mssola already said, I also would go forward with 2.3

**Comment by gitm1993** [comment] 2018-02-16 11:50
@mssola this version we use in production. I am not suer when we will update portus. I only have issue for fixing this.

@Vad1mo yes i think so. Question is why it doesnt use smtp a specified in config. enabled: false dosnt work. Anyway i thought enabled: false mean "dont use this smtp" thats why i changes to "true"

**Comment by gitm1993** [comment] 2018-02-16 11:51
@Vad1mo @mssola  go forward with 2.3.. does it mean that sending emails in 2.2 doesnt work?

**Comment by mssola** [comment] 2018-02-21 09:31
>  go forward with 2.3.. does it mean that sending emails in 2.2 doesnt work?

No, but we fixed some issues from 2.2 until now. The commits that fixed this issue (or at least I think it's the one you are facing because it's the same exception), are:

- c3ba1b50ca3148601ec2676b1cd930f016e93337: which does some extra checks on the configuration ([patch link](https://github.com/SUSE/Portus/commit/c3ba1b50ca3148601ec2676b1cd930f016e93337.patch)).
- 9d2ba47486932307b1fe7934b20a2938aa7fff84: which catches the exception you are facing and logs it ([patch link](https://github.com/SUSE/Portus/commit/9d2ba47486932307b1fe7934b20a2938aa7fff84.patch)).

This are included in both `master` and `2.3`, that's why I suggested to go for 2.3 directly. That being said, you can try applying the patches above.

That being said the patches above only wrap problems with the configuration, so if you have already fixed those issues then you don't need to apply them :wink:

**Comment by zstyblik** [comment] 2018-04-26 07:49
I'm running 2.2 and sending link to reset password works just fine. I'd suggest to check indentation as it can easily go wrong.

**Comment by mssola** [comment] 2018-04-27 06:36
Closing the issue. Shouldn't be reproducible for 2.3. If you have more questions, don't hesitate to add more comments here :+1:

**Closed by mssola** 2018-04-27 06:36 UTC
Labels: needs info
