### ISSUE TITLE
Any plan to implement repository delete API

### ISSUE THREAD

**Issue by farmerworking** [SUSE/Portus#533] opened 2015-11-05 08:50 UTC
If what I know is out of data please remind me. 

What I know is Delete image is not implemented right now in v2 registry. Only tag will be removed and data still remains in storage.

However this can still be useful since user can not pull image from this tag which kind of do the job of `delete a image`

From the what I saw from `rake routes` I can't see any API to implement this? please tell me what's in your mind about that

**Comment by mssola** [comment] 2015-11-05 13:40
Hi @farmerworking, even though this is a much requested feature, this is not possible yet due to a limitation on distribution's part. To get a better understanding of it, read this: https://github.com/docker/distribution/blob/master/ROADMAP.md#deletes.

Right now, we just experimented with it (see [this](https://github.com/SUSE/Portus/blob/master/bin/client.rb#L23) for example). The problem is that right now only soft deletes of blobs have been implemented. There are lots of proposals and ideas flying around, so if you're interested in this topic, I recommend that you subscribe at least to the main issues dealing with this in distribution.

It's not possible to remove tags either. For this, there's some work being done about making [tags first class citizens](https://github.com/docker/distribution/pull/173). Note that this will have some other consequences, besides deleting tags (e.g. an improved framework for tag notifications).

As it stands right now, from Portus side there's not much we can do (besides contributing to distribution). So right now, any issue on this direction has been labeled as [blocked](https://github.com/SUSE/Portus/labels/blocked). I'm going to close this issue now, since this is a duplicate of #197. If you want to keep on the discussion, please, do it on the issue #197.

Thanks for the interest!

**Closed by mssola** 2015-11-05 13:40 UTC
