### ISSUE TITLE
How to remove an image

### ISSUE THREAD

**Issue by toanvnu** [SUSE/Portus#678] opened 2016-01-23 17:44 UTC
I'm using portus for managing my docker images. Everything is great. But I can't see the button which removes an image.

**Comment by mssola** [comment] 2016-01-23 21:11
For now you can't. This is due a limitation on the registry's side. See #197 for more information.

**Comment by flavio** [comment] 2016-01-26 16:09
Closing as a duplicate of https://github.com/SUSE/Portus/issues/197

**Closed by flavio** 2016-01-26 16:09 UTC
