### ISSUE TITLE
Page to short, if alert and form are shown 

### ISSUE THREAD

**Issue by DirkHeinke** [SUSE/Portus#170] opened 2015-06-24 12:19 UTC
If the alert "No registry found. [...]" is shown and you open a from to create a new team or add an namespace, the height of the `<section>` is bigger than the body.

![protuscsse1](https://cloud.githubusercontent.com/assets/5230945/8329694/c31b0c5c-1a7b-11e5-8d1e-f7a17e653c04.png)

**Comment by mssola** [comment] 2015-06-25 13:19
I cannot reproduce this. Could you give us more info ?

**Comment by DirkHeinke** [comment] 2015-06-25 13:28
1. New setup with the warning "No registry found"
2. Have a browser with a small height or fill the page with so many entries, that you get a scrollbar
3. Open the from to add a new entry
4. You should see the same issue

**Comment by mssola** [comment] 2015-06-25 14:45
Ok, now I see, but note that this only happens in Chrome. It works fine in Firefox.

@cyntss can you look into this ?

**Comment by cyntss** [comment] 2015-10-13 12:21
Fixed in f4ee398a2bb96eb85d78d7883ba278b81ba8a672

**Closed by cyntss** 2015-10-13 12:21 UTC
Labels: ui
