### ISSUE TITLE
UI: small bug with search button in Firefox

### ISSUE THREAD

**Issue by dukas** [SUSE/Portus#532] opened 2015-11-05 07:19 UTC
![portus-design-bug](https://cloud.githubusercontent.com/assets/6458706/10962127/5bbd36e8-839e-11e5-8105-2ec28e8d1215.png)

Name        : Portus
Version     : 20151027090209
Release     : 1.1
Architecture: x86_64
This package has been built with commit bf76034e1bcc13bcf3f6e1b38b0ab9da8b76f0a2 from branch master on date Tue, 27 Oct 2015 09:02:09 +0000
Distribution: Virtualization:containers:Portus / openSUSE_13.2

P.S.
No problems in other browsers (opera, google chrome)

**Comment by mssola** [comment] 2015-11-05 09:13
I cannot reproduce this with firefox 41.0.1. So I guess that this only affects to Firefox 40 :/

**Comment by mssola** [comment] 2016-08-09 08:42
Closing this. I cannot reproduce it, and we've also made some changes on this regard. If you have more problems on this, feel free to re-open.

**Closed by mssola** 2016-08-09 08:42 UTC
Labels: ui
