### ISSUE TITLE
compose-setup.sh configure db failed

### ISSUE THREAD

**Issue by depay** [SUSE/Portus#448] opened 2015-10-19 07:57 UTC
Configuration executes successfully but fails during rm container, and it returns 1 instead of 0.
Now i add 'sleep 10' before that command and remove the checking loop below for working around it.

**Comment by flavio** [comment] 2015-10-19 08:04
Can you provide more details about how to reproduce the issue? Adding also a simple diff to this post would be great.

**Comment by depay** [comment] 2015-10-19 08:18
on both my fedora 22 & centos 7.1, devicemapper/overlayFS are both tested.

1, make "setup_database" in compose.sh as comment;
2, run `./compose-setup.sh`
3, run `docker-compose run --rm web rake db:create db:migrate db:seed` manually
4, `echo $?` it returns 1
5, the container exists in `docker ps -a`, like

~~~
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED              STATUS                          PORTS                              NAMES
ec64ee5c61d4        portus_web                                            "rake db:create db:mi"   About a minute ago   Exited (0) 20 seconds ago                                          portus_web_run_2
b926182a5dbc        portus_web:latest                                     "/usr/bin/supervisord"   About a minute ago   Up About a minute               3000/tcp                           portus_crono_1
ac3d94dead62        library/registry:2.1.1                                "/registry/entry.sh"     About a minute ago   Up About a minute               0.0.0.0:5000-5001->5000-5001/tcp   portus_registry_1
d85daef121b9        portus_web                                            "puma -b tcp://0.0.0."   About a minute ago   Up About a minute               0.0.0.0:3000->3000/tcp             portus_web_1
218f977a48e5        library/mariadb:latest                                "/docker-entrypoint.s"   About a minute ago   Up About a minute               3306/tcp                           portus_db_1
~~~

**Comment by flavio** [comment] 2015-10-19 08:22
Why are you running step #2 manually? This is already done by `./compose-setup`.

At the end of `./compose-setup.sh` everything is ready to be used.

**Comment by depay** [comment] 2015-10-19 08:48
since compose-setup doesn't work for me, it fails running that command with '--rm' again and again. Then i finally found the upper question, that cause `while [ $? -ne 0 ]; do` always failure.

**Comment by Salzig** [comment] 2015-10-30 22:05
Could you attach the ec64ee5c61d4 log (```docker logs ec64ee5c61d4```)?

**Comment by depay** [comment] 2015-11-02 01:46
@Salzig i tried just now, but there's nothing in output.. `STATUS` in `docker ps -a` is `Dead`.

**Comment by depay** [comment] 2015-11-02 01:51
and at the last of that command it told

Removing portus_web_run_1...
Cannot destroy container 4e448b467cb0629267b0daeb97bf3c96668001a7d61ffda6dc5bd035a7fe6348: Unable to remove filesystem for 4e448b467cb0629267b0daeb97bf3c96668001a7d61ffda6dc5bd035a7fe6348: remove /data/docker/containers/4e448b467cb0629267b0daeb97bf3c96668001a7d61ffda6dc5bd035a7fe6348: directory not empty

**Comment by Salzig** [comment] 2015-11-06 18:18
uhm, i guess this error is triggered by https://github.com/SUSE/Portus/blob/master/compose-setup.sh#L23, that would mean it's generated by Docker internally. What Version of Docker are you using?

**Comment by mssola** [comment] 2015-12-15 14:18
Hi @depay. There are multiple probable causes for this. 

- We've fixed a couple of issues regarding our docker-compose setup. Could you upgrade to the current master or v2 ?
- You should cleanup any previous generated files: `docker/environment` and `docker/registry/config.yml`.
- Make sure that you are using docker-compose 1.5.2. Compose 1.5.1 is known to contain a bug in which the `env_file` directive was not properly parsed (and therefore the DOCKER_HOST was not properly set in the Portus container).
- If you are using openSUSE and you are having problems, disable the firewall and restart the docker daemon, since SUSE's firewall might be messing with docker's networking.

With this in mind, could you try to run `./compose-setup.sh` again ?

**Comment by cyphar** [comment] 2015-12-23 09:07
@depay I'm going to close this for now. Feel free to reopen this if the above steps don't solve your problem, and post more information.

**Closed by cyphar** 2015-12-23 09:07 UTC
Labels: bug, docker-compose
