### ISSUE TITLE
ActionView::Template::Error (undefined method `[]' for nil:NilClass)

### ISSUE THREAD

**Issue by CRACKBOY** [SUSE/Portus#1717] opened 2018-03-07 16:31 UTC
I'm not unable to view docker images tags when I clic on repository name.

**Portus environement: (running in dockerized env)**
Portus: 2.3
Portus_bg: 2.3
registry: 2.6
mariadb: 10.0.23

[Error page](https://ibb.co/ivvik7)

**Error log**
`User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
portus_1     |    (0.1ms)  SELECT COUNT(*) FROM `registries`
portus_1     |   Repository Load (0.1ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`id` = 2 LIMIT 1
portus_1     |   Tag Load (0.4ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`repository_id` = 2
portus_1     |   Namespace Load (0.1ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 3 LIMIT 1
portus_1     |   Team Load (0.1ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`id` = 3 LIMIT 1
portus_1     |   User Exists (0.1ms)  SELECT  1 AS one FROM `users` INNER JOIN `team_users` ON `users`.`id` = `team_users`.`user_id` WHERE `team_users`.`team_id` = 3 AND `team_users`.`role` = 2 AND `users`.`id` = 2 LIMIT 1
portus_1     |   Star Exists (0.1ms)  SELECT  1 AS one FROM `stars` WHERE `stars`.`repository_id` = 2 AND `stars`.`user_id` = 2 LIMIT 1
portus_1     |   CACHE (0.0ms)  SELECT  1 AS one FROM `stars` WHERE `stars`.`repository_id` = 2 AND `stars`.`user_id` = 2 LIMIT 1  [["repository_id", 2]]
portus_1     |    (0.1ms)  SELECT COUNT(*) FROM `stars` WHERE `stars`.`repository_id` = 2
portus_1     |   Rendered repositories/show.html.slim within layouts/application (7.4ms)
portus_1     | Completed 401 Unauthorized in 14ms (ActiveRecord: 1.6ms)
portus_1     |
portus_1     | ActionView::Template::Error (undefined method `[]' for nil:NilClass):
portus_1     |     58:
portus_1     |     59:   .panel-body
portus_1     |     60:     <loading-icon v-if="isLoading"></loading-icon>
portus_1     |     61:
portus_1     |     62:     .table-responsive.tags
portus_1     |     63:       <tags-not-loaded v-if="notLoaded"></tags-not-loaded>
portus_1     |     64:       <tags-table v-if="!isLoading && !notLoaded" :tags="tags" :can-destroy="#{can_destroy?(@repository)}" :state="state" ></tags-table>
portus_1     |   lib/portus/security.rb:34:in `block in enabled?'
portus_1     |   lib/portus/security.rb:33:in `any?'
portus_1     |   lib/portus/security.rb:33:in `enabled?'
portus_1     |   app/helpers/repositories_helper.rb:42:in `security_vulns_enabled?'
portus_1     |   app/views/repositories/show.html.slim:61:in `_app_views_repositories_show_html_slim__2847231768104812650_70173464647840'
portus_1     |   app/controllers/repositories_controller.rb:26:in `show'
portus_1     |   app/middleware/catch_json_parse_errors.rb:11:in `call'
portus_1     |
portus_1     |
portus_1     | Processing by ErrorsController#show as HTML
portus_1     |   Parameters: {"id"=>"2", "status"=>"500"}
portus_1     |   Rendered errors/500.html.erb within layouts/errors (0.1ms)
portus_1     |   Rendered errors/_status_title.html.slim (0.0ms)
portus_1     | Completed 500 Internal Server Error in 5ms (Views: 4.2ms | ActiveRecord: 0.0ms)`

**Temporary found solution**
By removing **:security-enabled="#{security_vulns_enabled?}** from `app/views/repositories/show.html.slim` I successfully bypassed the error and get the tags page.

**Comment by mssola** [comment] 2018-03-12 15:40
I cannot reproduce this, but it's quite weird. From the logs I get that there is an exception here:

```ruby
    def self.enabled?
      ::Portus::Security::BACKENDS.any? do |b|
        APP_CONFIG["security"][b.config_key]["server"].present?  # <- HERE
      end
    end
```

Have you modified the given `config/config.yml` file ? Did you introduce a `config/config-local.yml` ? If so, what are the contents of it (remove passwords and other sensitive data first!) ? Are you providing any environment variables on this regard ?

**Comment by CRACKBOY** [comment] 2018-03-12 15:57
thank you @mssola  for answering!
here's my config.myl

`email:
  from: "portus@xxxxx"
  name: "Portus"
  reply_to: "portus-no-reply@xxxx"
  smtp:
    enabled: true
    address: "xxxxx"
    port: 25

ldap:
  enabled: true
  hostname: "xxxxx"
  port: 389
  method: "tls"
  base: "xxxxx"
  uid: "xxxxxx"
  authentication:
    enabled: true
    bind_dn: "xxxxx"
    password: "xxxx"

machine_fqdn:
  value: "xxxxxxx"

display_name:
  enabled: true

first_user_admin:
  enabled: true

delete:
  enabled: true
  contributors: false

gravatar:
  enabled: true

signup:
  enabled: false

check_ssl_usage:
  enabled: true

registry:
  jwt_expiration_time:
    value: 5

  catalog_page:
    value: 100

  timeout:
    value: 5

  read_timeout:
    value: 120

user_permission:
  change_visibility:
    enabled: true

  create_team:
    enabled: true

  manage_team:
    enabled: true

  create_namespace:
    enabled: true

  manage_namespace:
    enabled: true

  push_images:
    enabled: true

oauth:
  google_oauth2:
    enabled: false
  open_id:
    enabled: false
  github:
    enabled: false
  gitlab:
    enabled: false
  bitbucket:
    enabled: false

`

**Comment by mssola** [comment] 2018-03-12 16:31
Here's your problem, as specified in the [documentation](http://port.us.org/docs/Configuring-Portus.html) you should *never* modify the `config/config.yml` file. Instead you have two options described more thoroughly in the documentation:

1. Provide a `config/config-local.yml` file with the values you want to change from the `config/config-local.yml`.
2. Set environment variables (with the format described in the documentation).

All this is because the `config/config.yml` file acts as a file for default values, so Portus relies on this file being untouched.

**Comment by CRACKBOY** [comment] 2018-03-12 16:52
@mssola thank you for your time , 
I'll test that

kind regards,
Slim.

**Comment by mssola** [comment] 2018-03-13 07:25
Closing, but if you have more questions feel free to leave your comments here :+1:

**Closed by mssola** 2018-03-13 07:25 UTC
Labels: needs info
