### ISSUE TITLE
When CatalogJob removes dangling repo, it does not remove the activity table entries.

### ISSUE THREAD

**Issue by GrantStreetGroup** [SUSE/Portus#506] opened 2015-10-28 03:15 UTC
When CatalogJob removes 'dangling' repos from the repositories it fails to remove the corresponding entries in the activities table or the tags table. 

 This can cause the 'admin' page to fail with 

```
NoMethodError in Admin::Dashboard#index
Showing /portus/app/views/public_activity/repository/_push.html.slim where line #10 raised:

undefined method `namespace' for nil:NilClass
```

**Comment by mssola** [comment] 2015-10-28 10:07
Good catch.

**Comment by GrantStreetGroup** [comment] 2015-10-28 13:22
I only noticed this as the catalog job was failing to get a full catalog from the registry container.  That's a different issue I'm trying to dig into.

**Comment by mssola** [comment] 2015-10-28 13:33
@GrantStreetGroup this is most likely a duplicate of #441 ;) That is, the compose setup is currently broken. This is affecting you since the registry is basically not reachable...

**Comment by GrantStreetGroup** [comment] 2015-10-28 13:51
I'm not using compose...  I'm build my own images..   The issue only occurred because the registry returned a partial catalog.   This is due to a volume retention issue with the registry where it thinks it has a image, but does not report it in the catalog.  So a docker push reports that image are already present, which trigger a push event to Portus creating an activity.  When the catalog job runs later the pushed image is not reported.

**Comment by GrantStreetGroup** [comment] 2015-10-28 13:53
The issue did not occur when the registry was refusing the connection or unreachable.

**Comment by GrantStreetGroup** [comment] 2015-10-28 14:41
Think this is related to #443

**Comment by mssola** [comment] 2015-10-28 14:47
@GrantStreetGroup agreed

**Closed** 2015-10-28 18:40 UTC
Labels: bug
