### ISSUE TITLE
Pagination doesn't work in pages with more than one pagination

### ISSUE THREAD

**Issue by msfernandes** [SUSE/Portus#1028] opened 2016-08-10 01:47 UTC
The current pagination helper uses `page` as GET parameter. When the page contains more than one paginations, this parameter is changed in the controller and the pagination doesn't work anymore :(

For example, in `teams_controller#show` the used parameters are `users_page`and `namespaces_page`:

```
def show
  raise ActiveRecord::RecordNotFound if @team.hidden?

  authorize @team
  @team_users = @team.team_users.enabled.page(params[:users_page]).per(10)
  @team_namespaces = @team.namespaces.page(params[:namespaces_page]).per(15)
end
```

And the rendered pagination are:

```
<ul class="pagination">
  <li class="active"><a href="#">1</a></li>
  <li><a rel="next" href="/teams/5?page=2">2</a></li>
  <li><a rel="next" href="/teams/5?page=2">Next ›</a></li>
  <li><a href="/teams/5?page=2">Last »</a></li>
</ul>
```

I don't know which lib is used to do pagination in Portus but maybe this lib have an option to change the parameter's name.

**Comment by mssola** [comment] 2016-08-10 09:39
> I don't know which lib is used to do pagination in Portus but maybe this lib have an option to change the parameter's name.

The gem is called `kaminari`, and we are already doing that. See in the teams#show view:

```
  .panel-footer= paginate(@team_namespaces, param_name: 'namespaces_page')
```

Let me investigate.

**Comment by mssola** [comment] 2016-08-10 10:46
Moreover, it works for me :smile:. Could you tell how you were able to reproduce it ? As in, how many teams you created, team members, etc.

**Comment by vitoravelino** [comment] 2017-10-13 19:49
I guess this is not a valid bug anymore, so I'm closing it.

**Closed by vitoravelino** 2017-10-13 19:49 UTC
Labels: needs info
