### ISSUE TITLE
translation missing: en.devise.failure.user.ldap_bind_failed

### ISSUE THREAD

**Issue by draeron** [SUSE/Portus#1774] opened 2018-04-09 15:32 UTC
### Description

Missing proper error message with ldap. Please not, this not about ldap login working or not, just the error message when portus is misconfigured.

### Steps to reproduce

1. Enter invalid bind information in 
2. Try to login
3. Missing error message.

- **Expected behavior**: Get some error / tip which might help finding what is misconfigured
- **Actual behavior**: got a translation label id

### Deployment information

**Deployment method**: helm chart, v0.1.0
**Configuration**:

```yml
ldap:
  enabled: true

  hostname: "*****"
  port: 636

  # Available options: "plain", "simple_tls" and "starttls". The default is
  # "plain", the recommended is "starttls".
  method: simple_tls

  # The base where users are located (e.g. "ou=users,dc=example,dc=com").
  base: "OU=Users,DC=****,DC=com"

  # User filter (e.g. "mail=george*").
  filter: "(objectClass=person)"

  # The LDAP attribute where to search for username. The default is 'uid'.
  uid: "sAMAccountName"

  # LDAP credentials used to search for a user.
  authentication:
    enabled: true
    bind_dn: ****
    password: *****
  guess_email:
    enabled: false
    attr: 
```

**Portus version**: 2.3

**Comment by hiscal2015** [comment] 2018-04-10 02:24
https://github.com/SUSE/Portus/issues/1746

**Comment by mssola** [comment] 2018-05-02 08:45
as @hiscal2015 points out, it looks like a duplicate of #1746. I'll keep this open though.

**Closed** 2018-05-11 13:01 UTC
Labels: bug, duplicate
