### ISSUE TITLE
Public repos should be disable-able...

### ISSUE THREAD

**Issue by diranged** [SUSE/Portus#765] opened 2016-02-25 21:29 UTC
As an administrator I should be able to prevent everyone from marking a repo as `public` -- because after #468, a public repo is now fully accessible to anyone on the internet (if our service is out there).

**Comment by mssola** [comment] 2016-02-26 14:48
Closing since this appears to be a duplicate of #676. Feel free to re-open :wink:

**Comment by mssola** [comment] 2016-02-26 14:48
@diranged specifically, you can read [this](https://github.com/SUSE/Portus/issues/676#issuecomment-181379589) summing it up.

**Closed by mssola** 2016-02-26 14:48 UTC

**Comment by ghostsquad** [comment] 2018-06-05 21:52
@mssola this should be re-opened. I'd like to be able to prevent only hard-coded (in the config) repos from being public. Having some option to prevent repos from being made public I think was the point of this issue.
