### ISSUE TITLE
Can't log into dashboard

### ISSUE THREAD

**Issue by zkf9971** [SUSE/Portus#1395] opened 2017-08-24 02:54 UTC
Hi, I was planning to create a new user, so I can login with that new one. but admin user login to dashboard is not working, common user can't log into it either. I get the error like the attached screenshot:
![screen shot 2017-08-24 at 10 51 17](https://user-images.githubusercontent.com/1213101/29647142-3f35c36e-88ba-11e7-81f1-6a9698caf388.png)

From the log trace, I see following error.  Thanks for any help. 

```
App 112 stdout: ActionView::Template::Error (undefined method `display_username' for nil:NilClass):

App 112 stdout:     10:           - if activity.owner == activity.recipient

App 112 stdout:     11:             = "#{activity_owner(activity)} removed itself "

App 112 stdout:     12:           - else

App 112 stdout:     13:             = "#{activity_owner(activity)} removed user #{activity.recipient.display_username} "

App 112 stdout:     14:         = "from the "

App 112 stdout:     15:         = link_to activity.trackable.name, activity.trackable

App 112 stdout:     16:         |  team

App 112 stdout:   app/views/public_activity/team/_remove_member.html.slim:13:in `_app_views_public_activity_team__remove_member_html_slim___2332806370776785371_50301540'

App 112 stdout:   app/views/dashboard/index.html.slim:9:in `block in _app_views_dashboard_index_html_slim__2415825051262847868_43426440'

App 112 stdout:   app/views/dashboard/index.html.slim:8:in `_app_views_dashboard_index_html_slim__2415825051262847868_43426440'

App 112 stdout: 
```

**Comment by mssola** [comment] 2017-08-30 14:00
I cannot reproduce this problem:

1. Do you have a clear step-by-step guide on how to reproduce it ?
2. Which version (or commit) of Portus are you running on ?

**Comment by lobeck** [comment] 2018-01-31 13:19
This is probably caused by a deleted user or more specifically changelog entries for a user which no longer exists. Here's the example we've just seen:

    *************************** 1. row ***************************
                id: 42553
      trackable_id: 4
    trackable_type: Team
          owner_id: 13
        owner_type: User
               key: team.remove_member
        parameters: ---
    :role: owner
    
      recipient_id: 16
    recipient_type: User
        created_at: 2018-01-31 11:13:27
        updated_at: 2018-01-31 11:13:27
    *************************** 2. row ***************************
                id: 42556
      trackable_id: 16
    trackable_type: User
          owner_id: 13
        owner_type: User
               key: user.delete
        parameters: ---
    :username: redacted
    
      recipient_id: NULL
    recipient_type: NULL
        created_at: 2018-01-31 11:14:30
        updated_at: 2018-01-31 11:14:30
    2 rows in set (0.00 sec)

I got the exact same exception message. I was able to fix it by deleting `42553`, now the dashboard is loading again.

So i guess it can't handle the user being missing in the database, as there's no longer a user with id 16.

**Comment by mssola** [comment] 2018-02-15 11:35
@lobeck I cannot reproduce this on master (see screenshot), and 2.3 shouldn't be affected either. Which version are you using ?

![2018-02-15-123428_1916x1037_scrot](https://user-images.githubusercontent.com/767943/36254803-b9f59a36-124c-11e8-855f-19df2d586acc.png)

**Comment by lobeck** [comment] 2018-02-15 12:02
This was tested with 2.2. Can you repeat your test with the following steps:

- create user
- add user to group
- remove user from group
- delete user

The user actually needs to be deleted from the database. This might be fixed with 2.3 but currently i can't test this.

**Comment by mssola** [comment] 2018-02-15 12:35
Yeah, this is not reproducible in 2.3 or in master. Closing. Thanks for the feedback!

**Closed by mssola** 2018-02-15 12:35 UTC
Labels: bug, needs info

**Comment by lequanghoa** [comment] 2018-09-17 07:37
I got same issue when use docker portus latest version (Version: 2.3.3)

> Started GET "/admin/dashboard" for  at 2018-09-17 07:30:03 +0000
Processing by Admin::DashboardController#index as HTML
  Rendered public_activity/repository/_push.html.slim (119.8ms)
  Rendered public_activity/repository/_push.html.slim (39.4ms)
  Rendered public_activity/repository/_push.html.slim (2.6ms)
  Rendered public_activity/repository/_push.html.slim (19.3ms)
  Rendered public_activity/repository/_push.html.slim (19.1ms)
  Rendered public_activity/repository/_push.html.slim (40.5ms)
  Rendered public_activity/repository/_push.html.slim (20.4ms)
  Rendered public_activity/repository/_push.html.slim (2.3ms)
  Rendered public_activity/repository/_push.html.slim (20.0ms)
  Rendered public_activity/repository/_push.html.slim (39.9ms)
  Rendered public_activity/namespace/_create.html.slim (60.2ms)
  Rendered public_activity/repository/_push.html.slim (18.8ms)
  Rendered public_activity/repository/_push.html.slim (20.2ms)
  Rendered public_activity/user/_delete.html.slim (45.3ms)
  Rendered public_activity/namespace/_create.html.slim (40.4ms)
  Rendered public_activity/team/_create.html.slim (42.7ms)
  Rendered public_activity/repository/_push.html.slim (39.0ms)
  Rendered public_activity/team/_remove_member.html.slim (100.6ms)
  Rendered admin/dashboard/index.html.slim within layouts/application (917.0ms)
Completed 401 Unauthorized in 998ms (ActiveRecord: 214.4ms)

ActionView::Template::Error (undefined method `display_username' for nil:NilClass):
    10:           - if activity.owner == activity.recipient
    11:             = "#{activity_owner(activity)} removed itself "
    12:           - else
    13:             = "#{activity_owner(activity)} removed user #{activity.recipient.display_username} "
    14:         = "from the "
    15:         = link_to activity_team(activity), activity.trackable
    16:         |  team
  app/views/public_activity/team/_remove_member.html.slim:13:in `_app_views_public_activity_team__remove_member_html_slim___4308758539957256266_69869459651980'
  app/views/admin/dashboard/index.html.slim:75:in `block in _app_views_admin_dashboard_index_html_slim___2417512697876559968_69869454737800'
  app/views/admin/dashboard/index.html.slim:74:in `_app_views_admin_dashboard_index_html_slim___2417512697876559968_69869454737800'
  app/middleware/catch_json_parse_errors.rb:11:in `call'
