### ISSUE TITLE
On Ubuntu - Webpack::Rails::Manifest::ManifestLoadError in Auth::Registrations#new

### ISSUE THREAD

**Issue by Geekays** [SUSE/Portus#1307] opened 2017-07-01 07:20 UTC
I expected that the Portus installation will take care of the dependencies. However I'm getting this when I browse to the site - 

![image](https://user-images.githubusercontent.com/5683341/27760032-da8684b8-5e5b-11e7-9088-97e5b47e5340.png)

**Comment by mssola** [comment] 2017-07-03 09:26
Duplicate of #1245.

**Closed by mssola** 2017-07-03 09:26 UTC
