### ISSUE TITLE
Registry not synced with Portus Web

### ISSUE THREAD

**Issue by najeebdanish** [SUSE/Portus#946] opened 2016-06-30 20:46 UTC
I setup Portus using the demo docker-compose setup as per https://github.com/SUSE/Portus/wiki/Docker-Compose-Environment. I setup the registry as insecure. I can login to the registry fine from docker login and its pushing the image but I dont see it on Portus Web UI. When I look at the portus_registry_1 logs it says 

time="2016-06-30T20:40:16Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.3 http.request.host="389ds.illuminatics.local:5000" http.request.id=38eb3f58-1b26-4d39-8661-e5f3e46ffac7 http.request.method=GET http.request.remoteaddr="192.168.112.107:36026" http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \(linux\))" instance.id=89e871ee-f2ff-451b-bb26-319b24261f2f version=v2.3.1
192.168.112.107 - - [30/Jun/2016:20:40:16 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \(linux\))"
time="2016-06-30T20:40:16Z" level=error msg="response completed with error" auth.user.name=admin err.code="blob unknown" err.detail=sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f err.message="blob unknown to registry" go.version=go1.5.3 http.request.host="389ds.illuminatics.local:5000" http.request.id=635caec8-d88f-4c08-be3d-731b40372ecf http.request.method=HEAD http.request.remoteaddr="192.168.112.107:36028" http.request.uri="/v2/admin/busybox/blobs/sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \(linux\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=13.822184ms http.response.status=404 http.response.written=157 instance.id=89e871ee-f2ff-451b-bb26-319b24261f2f vars.digest="sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f" vars.name="admin/busybox" version=v2.3.1

**Comment by najeebdanish** [comment] 2016-06-30 20:54
Actually the very first time I push an image it says 
time="2016-06-30T20:52:43Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.3 http.request.host="389ds.illuminatics.local:5000" http.request.id=a09f0efb-c4cc-4c34-a27a-fc67aaa2f025 http.request.method=GET http.request.remoteaddr="192.168.112.107:36422" http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" instance.id=7da91e09-a94b-4860-81fe-f46c24ac9594 version=v2.3.1
192.168.112.107 - - [30/Jun/2016:20:52:43 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
time="2016-06-30T20:52:43Z" level=info msg="response completed" go.version=go1.5.3 http.request.host="389ds.illuminatics.local:5000" http.request.id=feee93a9-14fe-48ae-84cc-c542b74fa782 http.request.method=HEAD http.request.remoteaddr="192.168.112.107:36424" http.request.uri="/v2/admin/busybox/blobs/sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.contenttype="application/octet-stream" http.response.duration=21.053834ms http.response.status=200 http.response.written=0 instance.id=7da91e09-a94b-4860-81fe-f46c24ac9594 version=v2.3.1
192.168.112.107 - - [30/Jun/2016:20:52:43 +0000] "HEAD /v2/admin/busybox/blobs/sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f HTTP/1.1" 200 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
time="2016-06-30T20:52:43Z" level=info msg="response completed" go.version=go1.5.3 http.request.host="389ds.illuminatics.local:5000" http.request.id=f0435051-905f-4f02-80c4-9db1f7341d4d http.request.method=HEAD http.request.remoteaddr="192.168.112.107:36425" http.request.uri="/v2/admin/busybox/blobs/sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.contenttype="application/octet-stream" http.response.duration=15.695662ms http.response.status=200 http.response.written=0 instance.id=7da91e09-a94b-4860-81fe-f46c24ac9594 version=v2.3.1
192.168.112.107 - - [30/Jun/2016:20:52:43 +0000] "HEAD /v2/admin/busybox/blobs/sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749 HTTP/1.1" 200 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
time="2016-06-30T20:52:43Z" level=info msg="response completed" go.version=go1.5.3 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.host="389ds.illuminatics.local:5000" http.request.id=ebb4ad25-ba36-4f39-bcef-7fe6a5f9acce http.request.method=PUT http.request.remoteaddr="192.168.112.107:36427" http.request.uri="/v2/admin/busybox/manifests/latest" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.duration=6.945639ms http.response.status=201 http.response.written=0 instance.id=7da91e09-a94b-4860-81fe-f46c24ac9594 version=v2.3.1
192.168.112.107 - - [30/Jun/2016:20:52:43 +0000] "PUT /v2/admin/busybox/manifests/latest HTTP/1.1" 201 0 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
time="2016-06-30T20:52:44Z" level=error msg="retryingsink: error writing events: httpSink{http://389ds.illuminatics.local:3000/v2/webhooks/events}: error posting: Post http://389ds.illuminatics.local:3000/v2/webhooks/events: dial tcp 192.168.112.107:3000: getsockopt: no route to host (Client.Timeout exceeded while awaiting headers), retrying"
time="2016-06-30T20:52:45Z" level=error msg="retryingsink: error writing events: httpSink{http://389ds.illuminatics.local:3000/v2/webhooks/events}: error posting: Post http://389ds.illuminatics.local:3000/v2/webhooks/events: dial tcp 192.168.112.107:3000: getsockopt: no route to host (Client.Timeout exceeded while awaiting headers), retrying"
time="2016-06-30T20:52:46Z" level=error msg="retryingsink: error writing events: httpSink{http://389ds.illuminatics.local:3000/v2/webhooks/events}: error posting: Post http://389ds.illuminatics.local:3000/v2/webhooks/events: dial tcp 192.168.112.107:3000: getsockopt: no route to host (Client.Timeout exceeded while awaiting headers), retrying"
time="2016-06-30T20:52:47Z" level=error msg="retryingsink: error writing events: httpSink{http://389ds.illuminatics.local:3000/v2/webhooks/events}: error posting: Post http://389ds.illuminatics.local:3000/v2/webhooks/events: dial tcp 192.168.112.107:3000: getsockopt: no route to host (Client.Timeout exceeded while awaiting headers), retrying"

**Comment by mssola** [comment] 2016-07-01 17:05
Does Portus freeze after that? If so, I believe that this is a duplicate of #940. Could you confirm ?

**Comment by najeebdanish** [comment] 2016-07-07 20:01
Actually even before everything. When I login to the repository for the first time it gives me this

time="2016-07-07T19:53:22Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.5.3 http.request.host="389ds.illuminatics.local:5000" http.request.id=60e301ff-6544-4bfd-a827-2f6925f5abcb http.request.method=GET http.request.remoteaddr="192.168.112.107:38600" http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" instance.id=2423e6a0-f17f-4e8d-b476-f6c12651448d version=v2.3.1
192.168.112.107 - - [07/Jul/2016:19:53:22 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"
time="2016-07-07T19:53:23Z" level=info msg="response completed" go.version=go1.5.3 http.request.host="389ds.illuminatics.local:5000" http.request.id=5b5d2399-768e-4c3a-b61a-f2c779c633ac http.request.method=GET http.request.remoteaddr="192.168.112.107:38602" http.request.uri="/v2/" http.request.useragent="docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=14.929639ms http.response.status=200 http.response.written=2 instance.id=2423e6a0-f17f-4e8d-b476-f6c12651448d version=v2.3.1
192.168.112.107 - - [07/Jul/2016:19:53:23 +0000] "GET /v2/ HTTP/1.1" 200 2 "" "docker/1.11.2 go/go1.5.4 git-commit/b9f10c9 kernel/3.10.0-327.18.2.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.2 \\(linux\\))"




Let me see the other thread you are referring and confirm. But do you know based on these logs that why is it asking "authorization token required" when the user is an authentic user.

**Comment by s980672** [comment] 2017-06-16 00:25
I saw the same thing in my log, but portus seems to works well. 
What is happening when syncing between portus and registry?

**Comment by mssola** [comment] 2017-10-26 14:01
This should not happen anymore, the docker-compose setup and Portus in general has changed a lot and I cannot reproduce this in current master. So, I'm closing this issue, but feel free to re-open it if you can reproduce this with current master. Thanks 👍

**Closed by mssola** 2017-10-26 14:01 UTC
Labels: needs info
