### ISSUE TITLE
Webpack::Rails::Manifest::ManifestLoadError in Auth::Registrations#new

### ISSUE THREAD

**Issue by gnaga** [SUSE/Portus#1301] opened 2017-06-16 11:28 UTC
With latest version, below error is seen.

Showing /portus/app/views/layouts/authentication.html.slim where line #6 raised:

Could not load compiled manifest from /portus/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /portus/public/assets/webpack/manifest.json)
Extracted source (around line #6):
   
    title Portus
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag(*webpack_asset_paths("application"))
    = csrf_meta_tags
    meta content="width=device-width, initial-scale=1" name="viewport"
    link href="/favicon/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"

Rails.root: /portus

Application Trace | Framework Trace | Full Trace
app/views/layouts/authentication.html.slim:6:in `_app_views_layouts_authentication_html_slim__1598407697256649186_70334290620900'
app/controllers/auth/registrations_controller.rb:16:in `new'

**Comment by mssola** [comment] 2017-06-21 14:01
Duplicate of #1245 and #1260.

**Closed by mssola** 2017-06-21 14:01 UTC
