### ISSUE TITLE
Portus registry data cleared while pushing an image

### ISSUE THREAD

**Issue by gbisheimer** [SUSE/Portus#471] opened 2015-10-21 15:57 UTC
Portus interface shows no available repositories while pushing an image to the registry. Once the push ends, crono fill the db with update registry data again.

Tested on commit #ea5a398f38c0a4c103ea9890aaa1256c2deacd9c with docker-compose

**Comment by mssola** [comment] 2015-10-21 16:04
Hi @gbisheimer, this seems related to #441. That is, it seems that the docker-compose setup is broken when it comes to communicate with the registry... I'll fix this as soon as possible.

**Comment by mssola** [comment] 2015-12-15 10:31
This should be fixed by now. Make sure:

- To use the current master or v2, since there are some fixes regarding the set DOCKER_HOST.
- Cleanup any previous generated files: `docker/environment` and `docker/registry/config.yml`.
- Make sure that you are using docker-compose 1.5.2. Compose 1.5.0 and 1.5.1 are known to contain a bug in which the `env_file` directive was not properly parsed (and therefore the DOCKER_HOST was not properly set in the Portus container).
- If you are using openSUSE and you are having problems, disable the firewall and restart the docker daemon, since SUSE's firewall might be messing with docker's networking.

I'll try to update the docs about all this, but I'd prefer to get some confirmations first :)

**Comment by cyphar** [comment] 2015-12-23 09:04
I'm closing this for now. If it turns out that the issues are still reproducible after taking the above steps, feel free to reopen this with additional information.

**Closed by cyphar** 2015-12-23 09:04 UTC
Labels: bug, docker-compose
