### ISSUE TITLE
Webpack::Rails::Manifest

### ISSUE THREAD

**Issue by nujev** [SUSE/Portus#1291] opened 2017-05-30 18:36 UTC
![portus](https://cloud.githubusercontent.com/assets/220681/26599124/18cd35ba-453d-11e7-9bf5-e645a26d2590.png)

**Comment by jsilvaigor** [comment] 2017-05-30 19:19
+1

**Comment by mssola** [comment] 2017-05-31 07:33
Duplicate of #1245 and #1260. You need to run webpack in order to produce the manifest.json. This needs to be added in the documentation, and also be integrated into the different supported setups so this step is automatically handled. Sorry for the trouble.

**Closed by mssola** 2017-05-31 07:33 UTC

**Comment by nujev** [comment] 2017-05-31 21:16
Thanks for the help
