### ISSUE TITLE
repositories have disappeared

### ISSUE THREAD

**Issue by opichon** [SUSE/Portus#728] opened 2016-02-12 04:52 UTC
I was briefly able to make portus work. But after a couple of days, the repositories from the docker registry have disappeared. Portus refuses to list any repos in the registry.

docker login refuses to authenticate. Most of the time, I get this message:

Error response from daemon: no successful auth challenge for https://my.registry:5000/v2/ - errors: [token auth attempt to https://my.registry.com:5000/v2/ realm "https://portus.mydomain.com/v2/token" failed with status: 401 Unauthorized]

Occasionally I get the correct portus url: 
Error response from daemon: no successful auth challenge for https://my.registry:5000/v2/ - errors: [token auth attempt for registry https://my.registry:5000/v2/: https://portus.mydomain.com/v2/token?account=XXX&service=my.registry%3A5000 request failed with status: 401 Unauthorized]

It should be noted that this url works when opened in a browser: I get to authenticate and can get a token.

The registry has not been changed since last time portus worked, except for being restarted. 

The only change I made is on the portus server, when I ran "zypper update".

**Comment by mssola** [comment] 2016-02-12 13:35
> The only change I made is on the portus server, when I ran "zypper update"

It has happened to me sometimes on openSUSE that when I update with zypper, then the config for the registry gets replaced by the default one. Maybe this is your case ?

**Comment by mstad** [comment] 2016-06-02 14:28
Did anyone find any more detail on this?  I am seeing the same issue, have not yet found the culprit.

**Comment by mssola** [comment] 2016-06-03 07:28
@mstad could you tell me which versions of each program are you using ? (docker, distribution, Portus, etc). What kind of setup are you using ? Could you paste the logs whenever that happens ? It would be better if you have the `log_level` set to debug (see how to do that in the final section of [this](https://github.com/SUSE/Portus/blob/master/CONTRIBUTING.md#reporting-issues))

I'm asking all these questions because I'm not able to reproduce this so I'm basically blind when trying to fix this issue.

**Comment by mssola** [comment] 2017-10-25 13:10
Closing since no further information was given. Please re-open with more details if you can still reproduce this on latest master. Thanks for reporting 👍

**Closed by mssola** 2017-10-25 13:10 UTC
Labels: needs info
