### ISSUE TITLE
Docker image  libreadline.so.6 error

### ISSUE THREAD

**Issue by ondj** [SUSE/Portus#1510] opened 2017-11-09 11:01 UTC
When I try to start Portus from Docker on Centos, this error is showed and container exists right after this message:
```
# docker --version
Docker version 1.12.6, build 85d7426/1.12.6
# docker run opensuse/portus:2.2
/bin/bash: error while loading shared libraries: libreadline.so.6: cannot open shared object file: Permission denied
```

**Comment by nabadger** [comment] 2017-11-14 09:01
I have the same on coreos:

Container Linux by CoreOS 1465.6.0 (Ladybug)
```
/bin/bash: error while loading shared libraries: libreadline.so.6: cannot open shared object file: Permission denied
```
```
bash-4.3# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   a82d35e
 Built:        Wed Aug 16 00:03:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   a82d35e
 Built:        Wed Aug 16 00:03:08 2017
 OS/Arch:      linux/amd64
```

**Comment by nabadger** [comment] 2017-11-14 09:16
I don't get this error on 2.1 or head (only 2.2). I do however get a bunch of configuration errors, which are probably reloated to missing configs. 
```
Cannot load such file -- /srv/Portus/config/boot (LoadError)
```

**Comment by nabadger** [comment] 2017-11-14 09:27
```
bash-4.3# docker run -it --rm --entrypoint=/bin/sh opensuse/portus:2.2
/bin/sh: error while loading shared libraries: libreadline.so.6: cannot open shared object file: Permission denied
```

**Comment by nabadger** [comment] 2017-11-14 09:50
If I extract the layer on the 2.2 version I can see the file:

```
bash-4.3# ls -l fc3f9a0f2de3791a75ea91fc1affc1dd69175370d2dd4b126d9d870304f6cf2a/lib64/libreadline.so.6*

lrwxrwxrwx. 1 root root     18 Nov 10 13:45 libreadline.so.6 -> libreadline.so.6.3
-rwxr-xr-x. 1 root root 301032 May 16 14:08 libreadline.so.6.3
```

On portus:2.1 it was libreadline.so.6.2. 

Bit lost now - some kind of selinux issue?

**Comment by mcoreix** [comment] 2017-11-20 14:40
Get another version of Docker

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:46 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:27 2017
 OS/Arch:      linux/amd64
 Experimental: false

with this version it works :D

**Comment by mssola** [comment] 2018-01-17 08:02
I cannot reproduce this error. There was another issue with a weird Docker installation and CentOS, maybe it's the same problem ? If so, please refer to the distribution about this. If you have any more details that may clarify this issue, feel free to leave more comments.

I'll close it for now because this looks like a weird issue on the Docker side rather than in Portus. Thanks!

**Closed by mssola** 2018-01-17 08:02 UTC
