### ISSUE TITLE
Sign in issue

### ISSUE THREAD

**Issue by fii** [SUSE/Portus#1272] opened 2017-04-04 16:26 UTC
Could not load compiled manifest from /portus/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /portus/public/assets/webpack/manifest.json)

**Comment by mssola** [comment] 2017-04-10 14:12
Duplicate of #1245

**Closed by mssola** 2017-04-10 14:12 UTC
