### ISSUE TITLE
Portus not working the same using docker-compose or vagrantfile ?

### ISSUE THREAD

**Issue by xinity** [SUSE/Portus#308] opened 2015-09-07 12:03 UTC
hy all,

it seems Portus isn't working the same way using Vagrantfile or docker-compose, am i wrong ?
is this some kind of a bug or did i miss something relevant ? :)

**Comment by flavio** [comment] 2015-09-07 12:07
this looks like a duplicate of https://github.com/SUSE/Portus/issues/304.

**Closed by flavio** 2015-09-07 12:07 UTC

**Comment by xinity** [comment] 2015-09-07 12:09
absolutely not a duplicate :)
i've just figured out that registry is reachable using http :80 using the vagrantfile whereas for docker-compose it is reachable using http :5000

am i wrong ?

**Comment by flavio** [comment] 2015-09-07 12:14
Please provide more details next time.

You are not wrong. The setup produced by the Vagrantfile is different from the one produced by docker-compose.

The first one (vagrant) is meant for developers, there's a small private network where portus, registry and a docker client are operating. The only resource accessible from the outside of this private network is the UI of portus; however the registry is **not** accessible from the outside. This is almost useless for someone who wants to play a bit with ports (play == have a portus and registry instance accessible from all the computers on his network).

When using docker-compose all the services (portus and registry) are running on the same docker host, hence their port must be mapped to different ones to make them accessible to the network segment on which the docker host is connected.

**Comment by xinity** [comment] 2015-09-07 12:19
got it :)

thanks for answer.

i'll give more details next time , i promise :)
