### ISSUE TITLE
Portus can't reach docker registry with "compose-setup.sh" demo-deployment

### ISSUE THREAD

**Issue by cduch** [SUSE/Portus#560] opened 2015-11-12 12:34 UTC
I've followed the instructions to create a Portus demo-environment with the compose-setup.sh script in a freshly installed OpenSUSE 42.1 (with docker and docker-compose installed).

The compose-setup.sh script told me to:
```
Open http://172.17.42.1:3000 with your browser and perform the following steps:
  1 - Create an admin account
  2 - Add a new registry: choose a custom name, enter 172.17.42.1:5000 as hostname
```
I've created the account in step one.

I'm stuck at step 2 with the error:
```
Error: connection refused. The given registry is not available! You can skip this check by clicking on the "Skip remote checks" checkbox.
```
I skipped the check as advised and I was able to do a docker login with my credentials from step 1 on the cmd line. Even docker push works with the registry. But when I take a look in the Portus UI, the are no activities at all. 

The output of docker-compose ps:
```
      Name                     Command               State                       Ports                      
-----------------------------------------------------------------------------------------------------------
portus_crono_1      /usr/bin/supervisord             Up      3000/tcp                                       
portus_db_1         /docker-entrypoint.sh mysqld     Up      3306/tcp                                       
portus_registry_1   /registry/entry.sh               Up      0.0.0.0:5000->5000/tcp, 0.0.0.0:5001->5001/tcp 
portus_web_1        puma -b tcp://0.0.0.0:3000 ...   Up      0.0.0.0:3000->3000/tcp  
```
So I'm kinda stucked now.

**Comment by mssola** [comment] 2015-11-12 12:39
Sadly this is a known issue. See #441. I want to fix this situation as soon as possible, but I haven't had the time yet :( Even if this is a duplicate of #441, I'll keep this open.

**Comment by cyphar** [comment] 2015-12-15 09:00
@cduch Can you please post the version of `docker-compose` you are using? It should be noted that there's a bug in `1.5.1` which causes our configuration setup to not work. This upstream bug was fixed in `1.5.2`, and might solve your problem.

**Comment by cyphar** [comment] 2015-12-23 07:25
@cduch This should be fixed by now. Make sure:

- To use the current master or v2, since there are some fixes regarding how the DOCKER_HOST is set.
- Cleanup any previous generated files: `docker/environment` and `docker/registry/config.yml`.
- Make sure that you are using docker-compose 1.5.2. Compose 1.5.0 and 1.5.1 are known to contain a bug in which the `env_file` directive was not properly parsed (and therefore the DOCKER_HOST was not properly set in the Portus container).
- If you are using openSUSE and you are having problems, disable the firewall and restart the docker daemon, since SUSE's firewall might be messing with docker's networking.

**Comment by cyphar** [comment] 2015-12-23 09:03
I'm closing this for now. If it turns out that the issues are still reproducible after taking the above steps, feel free to reopen this with additional information.

**Closed by cyphar** 2015-12-23 09:03 UTC
Labels: bug, docker-compose

**Comment by ShapeOFwind** [comment] 2017-07-07 07:38
I met the problem: connection timeout, after the investigation found that the configuration is DNS, so can not find hostname:port
