### ISSUE TITLE
An user pushed an image but owner is portus

### ISSUE THREAD

**Issue by greatbn** [SUSE/Portus#1261] opened 2017-03-24 03:27 UTC
Hello Everybody. I'm use portus version 2.2.0. Does anyone have an issue same to me. When an user pushed an image to their repository. But Owner is portus. 
Like the picture 
<img src="http://i.imgur.com/fCaVwR7.png">

And these activities is portus user did
<img src="http://i.imgur.com/NJlXQ8v.png">
Thanks

**Comment by x3rus** [comment] 2017-05-26 01:17
Hi folks ,
I have the same issue 

 👍

**Comment by rumstattd** [comment] 2017-06-14 16:16
We have this issue also...   subscribing

**Comment by shortsteps** [comment] 2017-07-05 11:00
Hi all,
same issue for us using Release 2.2.0 zip.

It seems a regression over pull request #65 which was correctly solved and commited by @flavio a year ago.

**Comment by mssola** [comment] 2018-01-18 10:14
This is a duplicate of an issue grouped in #1599.

**Closed by mssola** 2018-01-18 10:14 UTC

**Comment by nadavsky** [comment] 2018-12-24 09:02
how can i fix this issue? portus 2.4 registry 2.6

**Comment by mssola** [comment] 2018-12-24 11:10
@nadavsky could you please add the logs from the `background` container and the `portus` container?

**Comment by nadavsky** [comment] 2018-12-25 15:36
[background.log](https://github.com/SUSE/Portus/files/2708865/background.log)
[portus.log](https://github.com/SUSE/Portus/files/2708866/portus.log)
![image](https://user-images.githubusercontent.com/30797502/50424409-abe5d580-086b-11e9-9435-66959f5faa20.png)

**Comment by vitoravelino** [comment] 2018-12-26 13:14
@nadavsky the `background.log` it too short and doesn't include the registry push event.

One question: were these images already in the registry before setting up portus?

**Comment by nadavsky** [comment] 2018-12-26 14:53
@vitoravelino "One question: were those images already in the registry before setting up portus?" 
no, they are new

**Comment by nadavsky** [comment] 2018-12-26 15:02
[background-e.log](https://github.com/SUSE/Portus/files/2710419/background-e.log)

**Comment by vitoravelino** [comment] 2018-12-26 15:19
There still no registry event on the log you've just attached. It's just the log when you were in the repository page where we keep fetching tags. Look for something like `actor` in the logs and that should be the piece that refers to the push event.

**Comment by nadavsky** [comment] 2018-12-27 13:42
[background.log](https://github.com/SUSE/Portus/files/2712534/background.log)
[clair.post] Handling code: 201
[clair.post] Handling code: 201
[clair.get] {"Layer"=>{"Name"=>"sha256:e356f185d289dd2c5e0658412fb89e00b4497ec71ec36f488e7b5b3c75bbbccc", "NamespaceName"=>"alpine:v3.8", "ParentName"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde", "IndexedByVersion"=>3, "Features"=>[{"Name"=>"libc-utils", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"0.7.1-r0", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"alpine-keys", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"2.1-r1", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"musl", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"1.1.19-r10", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"apk-tools", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"2.10.1-r0", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"libressl2.7-libssl", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"2.7.4-r0", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"busybox", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"1.28.4-r1", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"libstdc++", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"6.4.0-r9", "AddedBy"=>"sha256:e356f185d289dd2c5e0658412fb89e00b4497ec71ec36f488e7b5b3c75bbbccc"}, {"Name"=>"libgcc", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"6.4.0-r9", "AddedBy"=>"sha256:e356f185d289dd2c5e0658412fb89e00b4497ec71ec36f488e7b5b3c75bbbccc"}, {"Name"=>"alpine-baselayout", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"3.1.0-r0", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"zlib", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"1.2.11-r1", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"ssl_client", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"1.28.4-r1", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"libressl2.7-libcrypto", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"2.7.4-r0", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"musl-utils", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"1.1.19-r10", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"scanelf", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"1.2.3-r0", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}, {"Name"=>"libressl2.7-libtls", "NamespaceName"=>"alpine:v3.8", "VersionFormat"=>"dpkg", "Version"=>"2.7.4-r0", "AddedBy"=>"sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde"}]}}

**Comment by nadavsky** [comment] 2018-12-27 15:33
@vitoravelino  
see attached logs with "clair"
