### ISSUE TITLE
exec form of entrypoint

### ISSUE THREAD

**Issue by dohnto** [SUSE/Portus#390] opened 2015-10-05 14:19 UTC
Hello, when running `compose-setup.sh` from current master (d040ae6), it fails with

    ./compose-setup.sh 
    The setup will destroy the containers used by Portus, removing also their volumes.
    Are you sure to delete all the data? (Y/N)Y
    Killing portus_registry_1... done
    Killing portus_web_1... done
    Killing portus_db_1... done
    Going to remove portus_registry_1, portus_web_1, portus_db_1
    Removing portus_registry_1... done
    Removing portus_web_1... done
    Removing portus_db_1... done
    Creating portus_db_1...
    Creating portus_web_1...
    Creating portus_registry_1...
    Cannot start container 3c7a6aa9eed8d5aace99ae61a1b348df0f857c26957a0561c284e58e771180c7:  [8] System error: exec: "\"/registry/entry.sh\"": stat "/registry/entry.sh": no such file or directory

Log from docker daemon says:

    ERRO[0890] Handler for POST /containers/{name:.*}/start returned error: Cannot start container 3c7a6aa9eed8d5aace99ae61a1b348df0f857c26957a0561c284e58e771180c7: [8] System error: exec: "\"/registry/entry.sh\"": stat "/registry/entry.sh": no such file or directory 
    ERRO[0890] HTTP Error                                    err=Cannot start container 3c7a6aa9eed8d5aace99ae61a1b348df0f857c26957a0561c284e58e771180c7: [8] System error: exec: "\"/registry/entry.sh\"": stat "/registry/entry.sh": no such file or directory statusCode=404

My docker version is

    $ docker -v
    Docker version 1.7.0, build 0baf609
    $ docker-compose -v
    docker-compose version: 1.4.1

However, when I change the `docker-compose.yml` entrypoint to exec form: 

     entrypoint: ["/registry/entry.sh"]

everything works just fine. Is there a particular reason for using shell form of entrypoint?

Thanks in advance!

**Comment by mssola** [comment] 2015-12-15 10:42
This must be a regression from docker-compose. This should be fixed for the 1.5 branch. Note though that 1.5.0 and 1.5.1 are known to be broken in regards to parsing the `env_file` directive, and therefore our setup does not work properly there. Could you retry this on 1.5.2 ? Thanks

**Comment by cyphar** [comment] 2015-12-23 07:28
@dohnto Can you try again using `master`, and with Docker compose `1.5.2` or later? I can't reproduce this on `master`.

**Comment by mssola** [comment] 2016-02-23 10:30
I'm closing this since it's already fixed. Feel free to re-open this if you think it's still an issue.

**Closed by mssola** 2016-02-23 10:30 UTC
Labels: docker-compose
