### ISSUE TITLE
LDAP Completed 401 Unauthorized

### ISSUE THREAD

**Issue by drosskopp** [SUSE/Portus#1404] opened 2017-09-01 22:28 UTC
Hi,

got problems with LDAP-Auth.
A look with tcpdump and wireshark seems that communication with the ldap-server is successfull.
If I disable the LDAP suff everything works as expected.
Tried with clean environments.

On console with `docker-compose up` I got with LDAP-Auth:
```
portus_1    | Started POST "/users/sign_in" for 172.19.0.6 at 2017-09-01 21:30:22 +0000
portus_1    | Processing by Auth::SessionsController#create as HTML
portus_1    |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"xvTWEAsY/ANjkrZ1CmqP5Qmnl+lsRtTKvYkqH5MK8wCt1OGZQptgMj0j/YZrpKDHbwPtLV3puSZq7QSLlJ2DWg==", "user"=>{"username"=>"DRosskopp", "password"=>"[FILTERED]"}, "button"=>""}
portus_1    | Completed 401 Unauthorized in 30ms (ActiveRecord: 0.0ms)
portus_1    | Processing by Auth::SessionsController#new as HTML
portus_1    |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"xvTWEAsY/ANjkrZ1CmqP5Qmnl+lsRtTKvYkqH5MK8wCt1OGZQptgMj0j/YZrpKDHbwPtLV3puSZq7QSLlJ2DWg==", "user"=>{"username"=>"DRosskopp", "password"=>"[FILTERED]"}, "button"=>""}
portus_1    |   Rendered shared/_notification.html.slim (66.8ms)
portus_1    |   Rendered shared/_notification.html.slim (0.1ms)
portus_1    |   Rendered shared/_notifications.html.slim (76.4ms)
portus_1    |   Rendered devise/sessions/new.html.slim within layouts/authentication (111.5ms)
portus_1    | Completed 200 OK in 306ms (Views: 134.7ms | ActiveRecord: 4.2ms)
portus_1    | Started POST "/users/sign_in" for 172.19.0.6 at 2017-09-01 21:30:34 +0000
portus_1    | Processing by Auth::SessionsController#create as HTML
portus_1    |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"z8vBYEd1fYuodkehtkbX6k8C+aRM9frO9V//OWiGUw2k6/bpDvbhuvbHDFLXiPjIKaaDYH1alyIiO9GtbxEjVw==", "user"=>{"username"=>"DRosskopp", "password"=>"[FILTERED]"}, "button"=>""}
portus_1    | Completed 401 Unauthorized in 12ms (ActiveRecord: 0.0ms)
portus_1    | Processing by Auth::SessionsController#new as HTML
portus_1    |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"z8vBYEd1fYuodkehtkbX6k8C+aRM9frO9V//OWiGUw2k6/bpDvbhuvbHDFLXiPjIKaaDYH1alyIiO9GtbxEjVw==", "user"=>{"username"=>"DRosskopp", "password"=>"[FILTERED]"}, "button"=>""}
portus_1    |   Rendered shared/_notification.html.slim (0.1ms)
portus_1    |   Rendered shared/_notification.html.slim (0.1ms)
portus_1    |   Rendered shared/_notifications.html.slim (0.6ms)
portus_1    |   Rendered devise/sessions/new.html.slim within layouts/authentication (3.5ms)
portus_1    | Completed 200 OK in 149ms (Views: 5.4ms | ActiveRecord: 0.5ms)
crono_1     | I, [2017-09-01T21:39:52.892012 #45]  INFO -- : Perform CatalogJob
crono_1     | I, [2017-09-01T21:39:52.904989 #45]  INFO -- : Finished CatalogJob in 0.01 seconds
crono_1     | I, [2017-09-01T21:49:52.892633 #45]  INFO -- : Perform CatalogJob
crono_1     | I, [2017-09-01T21:49:52.898832 #45]  INFO -- : Finished CatalogJob in 0.01 seconds
```

Here a screenshot from wireshark:
![bildschirmfoto 2017-09-01 um 23 44 37](https://user-images.githubusercontent.com/26246494/29989040-f193370a-8f70-11e7-988e-8d5fbbc2ffb8.jpg)
Here a screenshot of http login:
![bildschirmfoto 2017-09-01 um 23 42 35](https://user-images.githubusercontent.com/26246494/29989079-1582e55c-8f71-11e7-94a6-8622b79b0bb0.jpg)

Checked out master branch to /srv/Portus and configured everything in examples/compose with valid certificates.

Relevant content of docker-compose.yml
```
version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      PORTUS_MACHINE_FQDN_VALUE: ${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      PORTUS_PRODUCTION_HOST: db
      PORTUS_PRODUCTION_DATABASE: portus_production
      PORTUS_PRODUCTION_PASSWORD: ${DATABASE_PASSWORD}

      # Secrets. It can possibly be handled better with Swarm's secrets.
      PORTUS_SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PORTUS_KEY_PATH: /certificates/hub.age.mpg.de.key
      PORTUS_PASSWORD: ${PORTUS_PASSWORD}

      # SSL
      PORTUS_PUMA_TLS_KEY: /certificates/hub.age.mpg.de.key
      PORTUS_PUMA_TLS_CERT: /certificates/hub.age.mpg.de.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #RAILS_SERVE_STATIC_FILES: 'true'
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - /srv/Portus/config/config-local.yml:/srv/Portus/config/config-local.yml:ro
      - static:/srv/Portus/public

  crono:
    image: opensuse/portus:head
    environment:
      PORTUS_MACHINE_FQDN_VALUE: ${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      PORTUS_PRODUCTION_HOST: db
      PORTUS_PRODUCTION_DATABASE: portus_production
      PORTUS_PRODUCTION_PASSWORD: ${DATABASE_PASSWORD}

      # Secrets. It can possibly be handled better with Swarm's secrets.
      PORTUS_SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PORTUS_KEY_PATH: /certificates/hub.age.mpg.de.key
      PORTUS_PASSWORD: ${PORTUS_PASSWORD}

      # We want to execute crono, not portus
      PORTUS_INIT_COMMAND: bin/crono
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - /srv/Portus/config/config-local.yml:/srv/Portus/config/config-local.yml:ro
```

Relevant Content of /srv/Portus/config/config-local.yml:
```
ldap:
  enabled: true
  hostname: "xxx.xxx.xxx.xxx"
  port: 389
  method: "plain"
  base: "ou=People,dc=xxx,dc=xxx,dc=de"
  filter: ""
  uid: "uid"

authentication:
  enabled: true
  bind_dn: "uid=xxxxx,ou=xxxxx,dc=xxx,dc=xxx,dc=xx"
  password: "xxxxxxxxxx"
```

If I comment out the ldap stuff in config-local.yml and restart the docker-compose everything works as expected. I can create a user in the db, login, connect to registry, etc.
I deleted all db and containers and tried it in a clean docker-compose environment with and without LDAP and every time the same result. Without db it's working, but not with ldap.
But if I sniff LDAP traffic with tcpdump on the hosts external interface it seems to work fine, so the fault should be inside the container.

Any suggestions or further debugging recommendations?

thx

**Comment by Vad1mo** [comment] 2017-09-01 22:33
what ldap are you using ActiveDirectory? Often its bind_dn and base that are not correct.

what helped me was to try it with http://directory.apache.org/studio/ first.

**Comment by drosskopp** [comment] 2017-09-01 22:59
First what I missed to say was that I changed the filter. /srv/Portus/config/config-local.yml looks different now than in wireshark. Tried different filters and without any.

To your Question:
We are using 389 Directory Server from redhat.
I tried ldapsearch from the host of this containers with success with same bind_dn and base:
```
ldapsearch -x -D "uid=xxxxxx,ou=specialusers,dc=xxx,dc=xxx,dc=de" -W -H ldap://xxx.xxx.xxx.xxx -b "dc=xxx,dc=xxx,dc=de" -s sub '(&(loginShell=/bin/bash)(homeDirectory=/beegfs/*)(uid=DRosskopp))'
Enter LDAP Password: 
# extended LDIF
#
# LDAPv3
# base <dc=xxx,dc=xxx,dc=de> with scope subtree
# filter: (&(loginShell=/bin/bash)(homeDirectory=/beegfs/*)(uid=DRosskopp))
# requesting: ALL
#

# DRosskopp, People, xxx
dn: uid=DRosskopp,ou=People,dc=xxx,dc=xxx,dc=de
homeDirectory: /beegfs/group_bit/home/DRosskopp
gidNumber: 1176
ageserviceaccess: xxxxxxx
ageserviceaccess: xxxxxxx
employeeType: ITGruppe
vpnGroup: xxxxxxxxxxx
sambaSID: S-1-5-21-xxxxxxxxxxx-xxxxxxxxxxx-xxxxxxxxxxx-xxxx
displayName: Daniel Rosskopp
sambaAcctFlags: [XU         ]
sambaDomainName: xxxxxxxx
uidNumber: 1412
gecos: Daniel Rosskopp
loginShell: /bin/bash
givenName: Daniel
sn: Rosskopp
cn: Daniel Rosskopp
uid: DRosskopp
mail: DRosskopp@xxx.xxx.de
mailAlternateAddress: Daniel.Rosskopp@xxx.xxx.de
sambaNTPassword: xxxxxxxxxxxxxxxxxxxxxxx
inetUserStatus: active
preferredLanguage: de
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: inetUser
objectClass: mailRecipient
objectClass: baltUser
objectClass: top
objectClass: posixAccount
objectClass: sambaSamAccount
objectClass: shadowAccount
userPassword:: xxxxxxxxxxxxxxxxxxx=
```

The LDAP filter `(&(loginShell=/bin/bash)(homeDirectory=/beegfs/*)` gives me a pearl syntax error so I did not use this in config-local.yml. Actually the filter is empty, but I tried different with also no success.
What is puzzeling me is that communication with ldap seems to success. It finds my object said wireshark.

**Comment by Vad1mo** [comment] 2017-09-01 23:04
hmm, no idea, try a newer version of the ldap gem. there is a branch (omniauth) that has the lastest version. You might give that a try.

**Comment by drosskopp** [comment] 2017-09-01 23:40
Out of my scope today ;-)

**Comment by drosskopp** [comment] 2017-09-02 01:19
Hi Vad1mo,

I tried it and it did not work, same result.

**Comment by mssola** [comment] 2017-09-04 13:22
@drosskopp just to be clear, the `authentication` part is embedded in the LDAP config. So instead of your:

```yaml
ldap:
  enabled: true
  hostname: "xxx.xxx.xxx.xxx"
  port: 389
  method: "plain"
  base: "ou=People,dc=xxx,dc=xxx,dc=de"
  filter: ""
  uid: "uid"

authentication:
  enabled: true
  bind_dn: "uid=xxxxx,ou=xxxxx,dc=xxx,dc=xxx,dc=xx"
  password: "xxxxxxxxxx"
```

It should be:

```yaml
ldap:
  enabled: true
  hostname: "xxx.xxx.xxx.xxx"
  port: 389
  method: "plain"
  base: "ou=People,dc=xxx,dc=xxx,dc=de"
  filter: ""
  uid: "uid"

  authentication:
    enabled: true
    bind_dn: "uid=xxxxx,ou=xxxxx,dc=xxx,dc=xxx,dc=xx"
    password: "xxxxxxxxxx"
```

Hopefully that was simply a copy&paste issue 😉 Otherwise, if you are using the containerized setup, why don't you use environment variables instead ? I think it would make the deployment easier for you.

**Comment by drosskopp** [comment] 2017-09-05 09:21
@mssola yes you are right. That was my fault. I have not seen that. You saved my day, thank's a lot, it works. :-D
Why I did not use environment variables. There are no environment variables shown for this on the side of the project https://github.com/openSUSE/docker-containers/blob/master/derived_images/portus/README.md. I tried to follow the syntax because I thought perhaps they are not documented but that did not work.
They wehre this style in my docker-compose:
```
#      PORTUS_LDAP_ENABLED: true
#      PORTUS_LDAP_HOSTNAME: "xxx.xxx.xxx.xxx"
#      PORTUS_LDAP_PORT: 389
#      PORTUS_LDAP_METHOD: "plain"
```
I also tried to add a folder like the one for registry named portus/crono with a config.yml in it, but this did not work also.
So how can I supply these environment variables to the docker image without bindmount /srv/Portus/config/config-local.yml?
thx

**Comment by mssola** [comment] 2017-09-05 10:20
Yeah, that should've worked, maybe this is related to #1386 ... It appears that the latest `head` image has some regression. I'll look into that later.

So, feel free to comment on that issue if you have more questions or info about this. For now I'm going to close this issue since it was resolved.

**Closed by mssola** 2017-09-05 10:20 UTC
Labels: needs info
