### ISSUE TITLE
push fails: "unauthorized: authentication required"

### ISSUE THREAD

**Issue by opichon** [SUSE/Portus#791] opened 2016-03-22 08:23 UTC
When trying to push an image to the registry, even though the user is correctly authenticated, the push fails with the message "unauthorized: authentication required". 

The user's ~/.docker/config.json file exists and shows that the user is authenticated.

``` bash
gitlab-runner@st3:~$ docker push dk1.united-asian.com:5000/uam/ssh-agent
The push refers to a repository [dk1.united-asian.com:5000/uam/ssh-agent]
d125f30d621b: Pushed
5f70bf18a086: Pushed
f9c383eacbb0: Pushed
daed1d495cec: Pushed
6b00b82071ac: Pushed
unauthorized: authentication required
```

Portus 2.0.0 installed via RPM.

Below are the relevant lines from the production log:

```
I, [2016-03-22T08:25:28.143584 #22705]  INFO -- : Started GET "/v2/token?account=op&scope=repository%3Auam%2Fssh-agent%3Apush%2Cpull&service=dk1.united-asian.com%3A5000" for 188.166.18.154 at 2016-03-22 08:25:28 +0000
I, [2016-03-22T08:25:28.144325 #22705]  INFO -- : Processing by Api::V2::TokensController#show as JSON
I, [2016-03-22T08:25:28.144376 #22705]  INFO -- :   Parameters: {"account"=>"op", "scope"=>"repository:uam/ssh-agent:push,pull", "service"=>"dk1.united-asian.com:5000"}
I, [2016-03-22T08:25:29.432970 #22705]  INFO -- : Completed 200 OK in 1289ms (Views: 0.1ms | ActiveRecord: 3.5ms)
```

The request when opened in a browser returns the appropriate authenticate token.

**Comment by opichon** [comment] 2016-03-22 08:28
Some other output from the command line. This time the intermediate layers also couldn't get pushed.

```bash
gitlab-runner@st3:/srv$ docker push dk1.united-asian.com:5000/uam/ssh-agent
The push refers to a repository [dk1.united-asian.com:5000/uam/ssh-agent]
d125f30d621b: Image push failed
5f70bf18a086: Image push failed
f9c383eacbb0: Image push failed
daed1d495cec: Preparing
6b00b82071ac: Image push failed
unauthorized: authentication required
```

**Comment by opichon** [comment] 2016-03-22 09:08
Now I also get, occasionally, "repository does not exist:.

gitlab-runner@st3:/srv$ docker push dk1.united-asian.com:5000/uam/ssh-agent
The push refers to a repository [dk1.united-asian.com:5000/uam/ssh-agent]
Repository does not exist: dk1.united-asian.com:5000/uam/ssh-agent
gitlab-runner@st3:/srv$ docker push dk1.united-asian.com:5000/uam/ssh-agent
The push refers to a repository [dk1.united-asian.com:5000/uam/ssh-agent]
Repository does not exist: dk1.united-asian.com:5000/uam/ssh-agent
g

**Comment by mssola** [comment] 2016-03-22 16:55
As far as I can see when you push an image some layers succeed and some others not. Which version of distribution are you using ? I'm asking this because we've fixed some issues with the latest distribution version. Check out Portus 2.0.3 (available as an RPM too), and see if you can still reproduce this. I remember having similar problems because I upgraded both docker and distribution, and if I didn't specify the tag (as you did), then I encountered similar problems.

Another problem you might be having is if this push takes a *lot* of time to be uploaded. This can be work-arounded with the [jwt_expiration_time](http://port.us.org/docs/Configuring-Portus.html#jwt-expiration-time) value.

**Comment by opichon** [comment] 2016-03-23 11:59
@mssola where is the rpm for Portus 2.0.3? I have refreshed the repository and tried to update, but it says the latest version is already installed. That's 2.0.0 as far as I can see.

**Comment by mssola** [comment] 2016-03-23 12:15
@opichon https://build.opensuse.org/project/repositories/Virtualization:containers:Portus:Release:2.0.3. I know it's a bit confusing to create a new obs subproject for each release... We are working on that.

**Comment by opichon** [comment] 2016-03-23 16:46
I've updated Portus to 2.0.3 but the problem persists.

**Comment by opichon** [comment] 2016-03-23 18:13
Actually, the Portus web server complains about the machine_fqdn setting.:

```
Please review your configuration
Fix secret machine fqdn value
You need to set the machine fdqn value for Portus to work. Set PORTUS_MACHINE_FQDN environment variable.
```

The machine_fqdn setting is correctly set in the /srv/Portus/config/config-local.yml file, as per the docs. The docs do not mention an environment variable. Is this new in Portus 2.0.3? Where should the environment variable be set? For what user?

**Comment by flavio** [comment] 2016-03-24 08:33
I think you accidentally closed the issue, reopening

**Comment by mssola** [comment] 2016-03-24 10:08
@opichon the fqdn is set as a secret in v2.0. Check what you have in `config/secrets.yml`. In master we moved this config value from the secrets file to the config file (so it's going to land in 2.1).

**Comment by opichon** [comment] 2016-03-25 02:58
I don't have any machine fqdn setting in config/secrets.yml. I don't believe I had either when running 2.0.0, and it seemed to have worked for a good while at least.

Anyway, what is the syntax for this setting in secrets.yml?

**Comment by opichon** [comment] 2016-03-25 03:04
I've added "machine_fqdn: ..." to the secrets.yml file. Now the site complains about "Something's wrong with our lighthouse." The production log only reports a 500 internal error without any detail. There is no lighthouse process running. Should there be?

**Comment by opichon** [comment] 2016-03-25 03:13
Should I run portusctl setup again I am loathe to do so because it needs to be run with ALL appropriate settings on the command line, and otherwise will erase my custom settings in config-local.yml. Isn't there a rake command that I can run to restart all services?

**Comment by opichon** [comment] 2016-03-25 03:53
This is the relevant part of the apache2 error log:
App 1706 stdout:
App 1706 stderr: WARN: Unresolved specs during Gem::Specification.reset:
App 1706 stderr:
App 1706 stderr:       rake (>= 0.8.1)
App 1706 stderr:
App 1706 stderr: WARN: Clearing out unresolved specs.
App 1706 stderr:
App 1706 stderr: Please report a bug if this causes problems.
App 1706 stderr:
App 1706 stderr: /usr/lib64/passenger/5.0.18/bin/passenger-config:32:in `require'
App 1706 stderr: :
App 1706 stderr: cannot load such file -- phusion_passenger
App 1706 stderr:  (
App 1706 stderr: LoadError
App 1706 stderr: )
App 1706 stderr:        from /usr/lib64/passenger/5.0.18/bin/passenger-config:32:in `<main>'
App 1723 stdout:

I've had this before occasionally. That was never resolved and I had to reinstall portus.

**Comment by flavio** [comment] 2016-03-29 10:24
What do you have inside of `production.logs`? I've seen this passenger error in the past, this is not what is causing the issue

**Comment by mssola** [comment] 2016-03-29 10:26
@opichon I don't think that `phusion_passenger` line is your main issue. I fear that there must be some miss-configuration after tweaking multiple files and running `portusctl` :/

If you are in production, the log output is minimized. You could try to increase the log level, restart portus and see what's being reported. You can do that by changing in `config/environments/production.rb`:

```ruby
config.log_level = :info
```

From `:info` to `:debug`. After doing more tests, remember to set back the log_level to :info, since it generates a lot of output :)

**Comment by mssola** [comment] 2017-10-26 11:05
Closing this since no further action was done. If you are still facing issues in master, please consider opening a new issue with the exact details. Thanks 👍

**Closed by mssola** 2017-10-26 11:05 UTC
Labels: needs info
