### ISSUE TITLE
Command `rake` error: Mysql2::Error: The used table type doesn't support FULLTEXT indexes: CREATE fulltext INDEX `fulltext_index_namespaces_on_name`  ON `namespaces`

### ISSUE THREAD

**Issue by summerQLin** [SUSE/Portus#450] opened 2015-10-19 10:31 UTC
Hi, 
I successfully use bundles to install all the gems. While run `rake` command, I got the error

```
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: The used table type doesn't support FULLTEXT indexes: CREATE fulltext INDEX `fulltext_index_namespaces_on_name`  ON `namespaces` (`name`)
```
Seems something wrong with the index type.

**Comment by flavio** [comment] 2015-10-19 10:35
This a deployment bug caused by your database being not configured properly or of a  version. I'm closing the issue since it's not a Portus bug.

However, to help you just check which version of MariaDB you are using. Make sure it's at least version 10.0. Ensure you are also using the right table type: https://mariadb.com/kb/en/mariadb/fulltext-index-overview/

**Closed by flavio** 2015-10-19 10:35 UTC

**Comment by depay** [comment] 2015-10-19 11:38
@summerQLin mariadb:5 doesn't support fulltext index, i also made that mistake before...

**Comment by summerQLin** [comment] 2015-10-19 12:18
@depay, I installed 10.0.21+maria-1~precise. 

But I failed to install gem mysql2. The error is `mysql client is missing. You may need to 'apt-get install libmysqlclient-dev' or 'yum install mysql-devel', and try again.` 

Then I run `sudo apt-get install libmysqlclient-dev`, error becomes `libmysqlclient-dev : Depends: libmysqlclient18 (= 5.5.44-0ubuntu0.14.04.1) but 10.0.21+maria-1~precise is to be installed`.

Isn't it funny? Could you please help?

**Comment by depay** [comment] 2015-10-20 01:54
@summerQLin i use docker-compose to run it successfully..and i've test on my host, after `zypper in libmysqlclient-devel`, `gem install mysql2` works.

**Comment by summerQLin** [comment] 2015-10-20 02:13
@depay I run docker-compose successfully, and I really like this product. Thanks for your great work! 

I hope I could contribute to it, and start to setup the development environment. So I get mariadb installed with root/portus username set. I changed the database.yml to use localhost as the host. Is it the right way to go?

**Comment by depay** [comment] 2015-10-20 03:39
@summerQLin if docker used, localhost is never your host. just add volume for `db` in docker-compose.yml as `/data/portus/db:/var/lib/mysql` to keep db data... if not docker, it seems ok...

**Comment by depay** [comment] 2015-10-20 03:39
@summerQLin if docker used, localhost is never your host. just add volume for `db` in docker-compose.yml as `/data/portus/db:/var/lib/mysql` to keep db data... if not docker, it seems ok...

**Comment by summerQLin** [comment] 2015-10-20 03:40
Finally I got that issue solved after run `apt-get install libmariadbclient-dev`, because libmysqlclient-dev always install the version that matches mariadb 5. But libmariadbclient-dev installed client lib for mariadb 10.

**Comment by summerQLin** [comment] 2015-10-20 03:47
@depay thanks, it's running the rspect tests.

I didn't use docker. What I plan to do is to run portus server(not docker) on one host, and setup registry(use docker) on another host which is configured to use portus as auth. So that I can code and debug. not sure if the plan will work.

**Comment by flavio** [comment] 2015-10-20 07:17
@summerQLin why don't you try the [vagrant setup](https://github.com/SUSE/Portus/wiki/The-development-environment)? That's what we use for development.

**Comment by wangchunyang** [comment] 2015-10-20 07:51
@flavio I just want to confirm that, does it mean we can use vagrant setup for day-to-day development of Portus? Just as what you did everyday.

**Comment by flavio** [comment] 2015-10-20 08:08
Sure, you can definitely do that.

**Comment by wangchunyang** [comment] 2015-10-21 07:39
@flavio thanks. Now I'm running three machines up with vagrant. It is cool! And I can access portus from host machine by http://localhost:5000/. If I changed the source of ruby, it will be reloaded automatically. Everything looks nice. However, I would like to run "bundle exec rspec spec" to test my changes. I guess that I should run it within "portus" machine. I tried it within portus machine, but I got the following erros:
```
vagrant@portus:/vagrant> bundle exec rspec spec
I, [2015-10-21T06:58:13.664935 #18623]  INFO -- : Not reporting to Code Climate because ENV['CODECLIMATE_REPO_TOKEN'] is not set.
: No such file or directory
Coverage report generated for RSpec to /vagrant/coverage. 89 / 203 LOC (43.84%) covered.
/usr/lib64/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:393:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

        bin/rake db:migrate RAILS_ENV=test

        from /usr/lib64/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:406:in `load_schema_if_pending!'
        from /usr/lib64/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:412:in `block in maintain_test_schema!'
        from /usr/lib64/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:640:in `suppress_messages'
        from /usr/lib64/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:417:in `method_missing'
        from /usr/lib64/ruby/gems/2.1.0/gems/activerecord-4.2.2/lib/active_record/migration.rb:412:in `maintain_test_schema!'
        from /vagrant/spec/rails_helper.rb:13:in `<top (required)>'
        from /vagrant/spec/api/v2/events_spec.rb:1:in `require'
        from /vagrant/spec/api/v2/events_spec.rb:1:in `<top (required)>'
        from /usr/lib64/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1327:in `load'
        from /usr/lib64/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
        from /usr/lib64/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1325:in `each'
        from /usr/lib64/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
        from /usr/lib64/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:102:in `setup'
        from /usr/lib64/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:88:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:73:in `run'
        from /usr/lib64/ruby/gems/2.1.0/gems/rspec-core-3.3.0/lib/rspec/core/runner.rb:41:in `invoke'
        from /usr/lib64/ruby/gems/2.1.0/gems/rspec-core-3.3.0/exe/rspec:4:in `<top (required)>'
        from /usr/bin/rspec:23:in `load'
        from /usr/bin/rspec:23:in `<main>'
```

Is there anything wrong with my steps?

**Comment by mssola** [comment] 2015-10-21 07:44
@wangchunyang apparently you have pending migrations. Run:

    $ bundle exec rake db:migrate

That should be it.

**Comment by wangchunyang** [comment] 2015-10-21 11:47
@mssola unfortunately I still got the same error. I even tried to destroy the vagant machines and up them again. I guess something is wrong in my steps.

1. On Windows, run "vagrant up" to start 3 machines
2. Run "vagrant ssh portus" to SSH to portus machine
3. Within portus machine, cd /vagrant
4. bundle exec rake db:migrate  (There is no anything output for this step)
5. bundle exec rspec spec
